# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Plotting On Crappy Graph Paper"
copyright = "2026, William Emerison Six"
author = "William Emerison Six"

version = "0.0.1"
release = "0.0.1"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = []

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

language = "en"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "alabaster"
html_static_path = ["_static"]

# =====================================================================
# gacalc book settings (originally generated by the sphinx-book-pipeline
# scaffold; those scripts are removed once the book builds, so the setup
# lives here now -- see the repo's git history for how it was produced)
# ---------------------------------------------------------------------
# Python reads this file from top to bottom, so anything we set again
# down here OVERRIDES the default that sphinx-quickstart wrote above
# (for example, the HTML theme).
# =====================================================================

# The "furo" theme: clean, modern, automatic light/dark. Same theme the
# modelviewprojection book uses, instead of the Sphinx default.
html_theme = "furo"

# Our own stylesheet, loaded on top of the theme's own CSS. It lives in
# the _static/ folder that sphinx-quickstart created.
html_css_files = ["custom.css"]

# The Sphinx add-ons ("extensions") this book turns on:
extensions = [
    "sphinx.ext.autodoc",  # copy docstrings out of the gacalc source
    "sphinx.ext.napoleon",  # read Google / NumPy style docstrings
    "sphinx.ext.viewcode",  # add a "[source]" link beside documented code
    "sphinx.ext.mathjax",  # draw the math in the HTML using MathJax
    "sphinx.ext.imgconverter",  # convert SVG pictures so the PDF can use them
    "nbsphinx",  # let Jupyter notebooks become book pages
    "myst_nb",  # kept exactly as modelviewprojection has it
]

# How autodoc behaves: document every member, keep them in source order,
# and include the __init__ / __call__ / arithmetic operator methods that
# a geometric-algebra library actually cares about.
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__, __call__, __add__, __sub__, __mul__, __rmul__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}

# Tell MathJax which delimiters mean "this is math":
#   $...$  and  \(...\)   for math inside a sentence
#   $$...$$ and \[...\]   for a centered equation on its own line
mathjax3_config = {
    "tex": {
        "inlineMath": [["$", "$"], ["\\(", "\\)"]],
        "displayMath": [["$$", "$$"], ["\\[", "\\]"]],
    },
}

# ---- PDF (LaTeX) settings -------------------------------------------
# Build the PDF with LuaLaTeX instead of the default pdfLaTeX. Reason:
# gacalc's docstrings contain real Unicode math characters (things like
# the square-root sign and subscripts). pdfLaTeX stops with an error on
# those; LuaLaTeX prints them just fine.
latex_engine = "lualatex"

# Left to itself LuaLaTeX would switch the index builder to "xindy",
# which drags in a large extra dependency. The plain "makeindex" is
# perfectly good for this book, so keep it.
latex_use_xindy = False

# A short LaTeX preamble so pictures stay where we put them and default
# to half the text width. r"""...""" is a "raw" string, meaning the
# backslashes are kept exactly as typed.
latex_elements = {
    "preamble": r"""
\usepackage{graphicx}
\usepackage{float}
\makeatletter
\def\fps@figure{H}
\setkeys{Gin}{width=0.5\textwidth}
\makeatother
""",
}

# A couple of Markdown niceties, matching modelviewprojection.
myst_enable_extensions = ["colon_fence", "dollarmath"]

# If a notebook page is slow to run, allow up to ten minutes for it.
nb_execution_timeout = 600
