import Mathlib

/-! # 𝒢₃ from scratch: the 8-dimensional Euclidean geometric algebra

    A self-contained construction of the 3D geometric algebra over ℝ in the basis
    {1, e₁, e₂, e₃, e₁ * e₂, e₁ * e₃, e₂ * e₃, e₁ * e₂ * e₃}, Euclidean signature (eᵢ²=1, eᵢeⱼ=−eⱼeᵢ).
    Built the same way as `G2`: a coordinate struct whose fields are the eight real
    **coefficients**, with the basis blades exposed as genuine `G3` **elements**
    (`one`/`e_1`/…/`e_123`) — a basis vector is a vector, not a real.

    The shared prerequisite for the 3D proofs (projection, dot, wedge, pseudoscalar,
    the rotation sandwich) — see `tasks/reference/lean-ga-proof-architecture.md` and the umbrella
    `tasks/archive/2026/10/04/investigate-lean-proofs-for-ga.md` (archived).

    **The geometric product / wedge / reverse formulas are NOT hand-derived** — they were
    generated by running gacalc's reference `Gn` on two fully-symbolic 3D multivectors and
    transcribed verbatim (`tools/derive_lean_algebra.py`), so the product
    is correct-by-construction against gacalc, the oracle. The multiplication-table lemmas
    below (`e_1_sq`, `e_1_mul_e_2`, the anticommutation, `I_sq`) then independently confirm
    the transcription. -/
namespace GacalcProofs

/-- An element of 𝒢₃, stored by its eight real coefficients on the basis blades. The
    fields are coefficients (reals); the basis blades are the elements `one`/`e_1`/…/`e_123`
    below. `@[ext]` gives componentwise extensionality for the `ext` tactic. -/
@[ext]
structure G3 where
  s : ℝ    -- coefficient of the scalar unit 1      (grade 0)
  c1 : ℝ   -- coefficient of e₁                       (grade 1)
  c2 : ℝ   -- coefficient of e₂                       (grade 1)
  c3 : ℝ   -- coefficient of e₃                       (grade 1)
  c12 : ℝ  -- coefficient of e₁ * e₂                     (grade 2)
  c13 : ℝ  -- coefficient of e₁ * e₃                     (grade 2)
  c23 : ℝ  -- coefficient of e₂ * e₃                     (grade 2)
  c123 : ℝ -- coefficient of e₁ * e₂ * e₃ (pseudoscalar)    (grade 3)

namespace G3

/-- The Euclidean geometric product in 𝒢₃ (transcribed from gacalc's `Gn` via
    `tools/derive_lean_algebra.py`). `noncomputable` (ℝ field ops). -/
noncomputable def mul (a b : G3) : G3 where
  s :=
    a.c1 * b.c1 - a.c12 * b.c12 - a.c123 * b.c123 - a.c13 * b.c13 + a.c2 * b.c2
      - a.c23 * b.c23 + a.c3 * b.c3 + a.s * b.s
  c1 :=
    a.c1 * b.s + a.c12 * b.c2 - a.c123 * b.c23 + a.c13 * b.c3 - a.c2 * b.c12
      - a.c23 * b.c123 - a.c3 * b.c13 + a.s * b.c1
  c2 :=
    a.c1 * b.c12 - a.c12 * b.c1 + a.c123 * b.c13 + a.c13 * b.c123 + a.c2 * b.s
      + a.c23 * b.c3 - a.c3 * b.c23 + a.s * b.c2
  c3 :=
    a.c1 * b.c13 - a.c12 * b.c123 - a.c123 * b.c12 - a.c13 * b.c1 + a.c2 * b.c23
      - a.c23 * b.c2 + a.c3 * b.s + a.s * b.c3
  c12 :=
    a.c1 * b.c2 + a.c12 * b.s + a.c123 * b.c3 - a.c13 * b.c23 - a.c2 * b.c1
      + a.c23 * b.c13 + a.c3 * b.c123 + a.s * b.c12
  c13 :=
    a.c1 * b.c3 + a.c12 * b.c23 - a.c123 * b.c2 + a.c13 * b.s - a.c2 * b.c123
      - a.c23 * b.c12 - a.c3 * b.c1 + a.s * b.c13
  c23 :=
    a.c1 * b.c123 - a.c12 * b.c13 + a.c123 * b.c1 + a.c13 * b.c12 + a.c2 * b.c3
      + a.c23 * b.s - a.c3 * b.c2 + a.s * b.c23
  c123 :=
    a.c1 * b.c23 + a.c12 * b.c3 + a.c123 * b.s - a.c13 * b.c2 - a.c2 * b.c13
      + a.c23 * b.c1 + a.c3 * b.c12 + a.s * b.c123

/-- The outer (wedge) product in 𝒢₃ (also transcribed from gacalc's `Gn`). -/
noncomputable def wedge (a b : G3) : G3 where
  s := a.s * b.s
  c1 := a.c1 * b.s + a.s * b.c1
  c2 := a.c2 * b.s + a.s * b.c2
  c3 := a.c3 * b.s + a.s * b.c3
  c12 := a.c1 * b.c2 + a.c12 * b.s - a.c2 * b.c1 + a.s * b.c12
  c13 := a.c1 * b.c3 + a.c13 * b.s - a.c3 * b.c1 + a.s * b.c13
  c23 := a.c2 * b.c3 + a.c23 * b.s - a.c3 * b.c2 + a.s * b.c23
  c123 :=
    a.c1 * b.c23 + a.c12 * b.c3 + a.c123 * b.s - a.c13 * b.c2 - a.c2 * b.c13
      + a.c23 * b.c1 + a.c3 * b.c12 + a.s * b.c123

/-- Componentwise addition. -/
noncomputable def add (a b : G3) : G3 :=
  ⟨a.s + b.s, a.c1 + b.c1, a.c2 + b.c2, a.c3 + b.c3,
   a.c12 + b.c12, a.c13 + b.c13, a.c23 + b.c23, a.c123 + b.c123⟩

/-- Componentwise subtraction. -/
noncomputable def sub (a b : G3) : G3 :=
  ⟨a.s - b.s, a.c1 - b.c1, a.c2 - b.c2, a.c3 - b.c3,
   a.c12 - b.c12, a.c13 - b.c13, a.c23 - b.c23, a.c123 - b.c123⟩

/-- Componentwise negation. -/
noncomputable def neg (a : G3) : G3 :=
  ⟨-a.s, -a.c1, -a.c2, -a.c3, -a.c12, -a.c13, -a.c23, -a.c123⟩

/-- Scalar multiple. -/
noncomputable def smul (r : ℝ) (a : G3) : G3 :=
  ⟨r * a.s, r * a.c1, r * a.c2, r * a.c3,
   r * a.c12, r * a.c13, r * a.c23, r * a.c123⟩

/-- Reverse `R̃` — grade sign (−1)^(k(k−1)/2): grades 0,1 fixed, grades 2,3 negated
    (transcribed from gacalc; matches the G2 reverse pattern extended to grade 3). -/
noncomputable def reverse (a : G3) : G3 :=
  ⟨a.s, a.c1, a.c2, a.c3, -a.c12, -a.c13, -a.c23, -a.c123⟩

/-! ### Basis blades as genuine `G3` elements -/

def one : G3 := ⟨1, 0, 0, 0, 0, 0, 0, 0⟩
def e_1 : G3 := ⟨0, 1, 0, 0, 0, 0, 0, 0⟩
def e_2 : G3 := ⟨0, 0, 1, 0, 0, 0, 0, 0⟩
def e_3 : G3 := ⟨0, 0, 0, 1, 0, 0, 0, 0⟩
def e_12 : G3 := ⟨0, 0, 0, 0, 1, 0, 0, 0⟩
def e_13 : G3 := ⟨0, 0, 0, 0, 0, 1, 0, 0⟩
def e_23 : G3 := ⟨0, 0, 0, 0, 0, 0, 1, 0⟩
def e_123 : G3 := ⟨0, 0, 0, 0, 0, 0, 0, 1⟩

/-- A grade-1 vector from its three coordinates. -/
def vec (x y z : ℝ) : G3 := ⟨0, x, y, z, 0, 0, 0, 0⟩

/-- The unit pseudoscalar I₃ = e₁ * e₂ * e₃. -/
def I : G3 := e_123

/-! ### The geometric-product multiplication table (confirms the transcription) -/

theorem e_1_sq : mul e_1 e_1 = one := by simp only [mul, e_1, one]; ext <;> ring
theorem e_2_sq : mul e_2 e_2 = one := by simp only [mul, e_2, one]; ext <;> ring
theorem e_3_sq : mul e_3 e_3 = one := by simp only [mul, e_3, one]; ext <;> ring

/-- e₁ * e₂ = e₁₂ (the bivector is the product of the two basis vectors). -/
theorem e_1_mul_e_2 : mul e_1 e_2 = e_12 := by simp only [mul, e_1, e_2, e_12]; ext <;> ring
theorem e_1_mul_e_3 : mul e_1 e_3 = e_13 := by simp only [mul, e_1, e_3, e_13]; ext <;> ring
theorem e_2_mul_e_3 : mul e_2 e_3 = e_23 := by simp only [mul, e_2, e_3, e_23]; ext <;> ring

/-- e₂ * e₁ = −e₁₂ (orthogonal basis vectors anticommute). -/
theorem e_2_mul_e_1 : mul e_2 e_1 = neg e_12 := by
  simp only [mul, e_2, e_1, e_12, neg]; ext <;> ring

/-- e₁ * e₂ * e₃ = e₁₂₃ (the pseudoscalar is the product of the three basis vectors). -/
theorem e_12_mul_e_3 : mul e_12 e_3 = e_123 := by
  simp only [mul, e_12, e_3, e_123]; ext <;> ring

/-- **The pseudoscalar squares to −1:** I₃² = −1 = (−1)^(3 * 2/2). -/
theorem I_sq : mul I I = neg one := by simp only [mul, I, e_123, neg, one]; ext <;> ring

/-- Reverse is an involution. -/
theorem reverse_reverse (a : G3) : reverse (reverse a) = a := by
  simp only [reverse]; ext <;> ring

/-! ### The dual, the dot, and bilinearity helpers (for projection) -/

/-- The zero multivector. -/
def zero : G3 := ⟨0, 0, 0, 0, 0, 0, 0, 0⟩

/-- A **bivector** `p·e₁₂ + q·e₁₃ + r·e₂₃` (grade 2), naming just the three bivector coefficients on
    top of `zero` — self-documenting in place of the raw literal `⟨0,0,0,0,p,q,r,0⟩`. -/
def bivector (p q r : ℝ) : G3 := { zero with c12 := p, c13 := q, c23 := r }

/-- A **trivector** (pseudoscalar) `t·e₁₂₃` (grade 3), in place of `⟨0,0,0,0,0,0,0,t⟩`. -/
def trivector (t : ℝ) : G3 := { zero with c123 := t }

/-- A **scalar** `a` (grade 0) as a 𝒢₃ element, in place of `⟨a,0,0,0,0,0,0,0⟩`. -/
def scalar (a : ℝ) : G3 := { zero with s := a }

/-- The scalar product ⟨A B⟩₀ — the scalar part of the geometric product. For two
    vectors this is the Euclidean dot product `a₁ * b₁ + a₂ * b₂ + a₃ * b₃`. -/
noncomputable def dot (a b : G3) : ℝ := (mul a b).s

/-- `dot` distributes over subtraction on the left (it is bilinear). -/
theorem dot_sub_left (u w v : G3) : dot (sub u w) v = dot u v - dot w v := by
  simp only [dot, mul, sub]; ring

/-- `dot` pulls out a scalar on the left. -/
theorem dot_smul_left (k : ℝ) (u v : G3) : dot (smul k u) v = k * dot u v := by
  simp only [dot, mul, smul]; ring

/-- `dot` distributes over addition on the right (bilinear on the right too). -/
theorem dot_add_right (u v w : G3) : dot u (add v w) = dot u v + dot u w := by
  simp only [dot, mul, add]; ring

/-- `dot` distributes over subtraction on the right. -/
theorem dot_sub_right (u v w : G3) : dot u (sub v w) = dot u v - dot u w := by
  simp only [dot, mul, sub]; ring

/-- `dot` pulls out a scalar on the right. -/
theorem dot_smul_right (k : ℝ) (u v : G3) : dot u (smul k v) = k * dot u v := by
  simp only [dot, mul, smul]; ring

/-- The wedge distributes over subtraction on the right. -/
theorem wedge_sub_right (a u w : G3) : wedge a (sub u w) = sub (wedge a u) (wedge a w) := by
  simp only [wedge, sub]; ext <;> ring

/-- The wedge pulls out a scalar on the right. -/
theorem wedge_smul_right (k : ℝ) (a u : G3) : wedge a (smul k u) = smul k (wedge a u) := by
  simp only [wedge, smul]; ext <;> ring

/-- The wedge distributes over addition on the right. -/
theorem wedge_add_right (a u w : G3) : wedge a (add u w) = add (wedge a u) (wedge a w) := by
  simp only [wedge, add]; ext <;> ring

/-- A vector wedged with itself is zero. -/
theorem wedge_self_vec_coord (x y z : ℝ) : wedge (vec x y z) (vec x y z) = zero := by
  simp only [wedge, vec, zero]; ext <;> ring

/-- **The fundamental identity `a b = a·b + a∧b` for vectors** (Hestenes' defining relation):
    the geometric product of two vectors splits into its scalar (inner) part `a·b` and its
    bivector (outer) part `a∧b`. Unconditional; pure `ring`. -/
theorem vec_mul_eq_dot_add_wedge (a1 a2 a3 b1 b2 b3 : ℝ) :
    mul (vec a1 a2 a3) (vec b1 b2 b3)
      = add (smul (dot (vec a1 a2 a3) (vec b1 b2 b3)) one)
            (wedge (vec a1 a2 a3) (vec b1 b2 b3)) := by
  simp only [mul, wedge, smul, one, dot, add, vec]; ext <;> ring

/-- **Orthogonal vectors' geometric product is their wedge:** for vectors with `a · b = 0`,
    `a b = a ∧ b`. A corollary of the fundamental identity — orthogonality kills the scalar part,
    leaving only the bivector. This is what turns `a (b − proj_a b)` into the plane bivector
    `a ∧ b` (with `r = b − proj_a b ⊥ a`) — the step that reduces the 3D versor sandwich to 2D. -/
theorem vec_mul_perp (a1 a2 a3 b1 b2 b3 : ℝ)
    (h : dot (vec a1 a2 a3) (vec b1 b2 b3) = 0) :
    mul (vec a1 a2 a3) (vec b1 b2 b3) = wedge (vec a1 a2 a3) (vec b1 b2 b3) := by
  rw [vec_mul_eq_dot_add_wedge, h]
  simp only [smul, one, add]; ext <;> ring

/-- A multivector is a **vector** (grade 1) exactly when its scalar, bivector and pseudoscalar parts
    vanish. The proofs carry no vector subtype, so this predicate is how "`a` is a vector" is stated for
    an arbitrary `a : G3` (as opposed to a coordinate literal `vec …`). -/
def IsVector (a : G3) : Prop :=
  a.s = 0 ∧ a.c12 = 0 ∧ a.c13 = 0 ∧ a.c23 = 0 ∧ a.c123 = 0

/-- A grade-1 multivector is the `vec` of its own vector coordinates — the bridge from an abstract
    vector to the coordinate literal the `vec …` lemmas are stated on. -/
theorem eq_vec_of_isVector {a : G3} (ha : IsVector a) : a = vec a.c1 a.c2 a.c3 := by
  obtain ⟨hs, h12, h13, h23, h123⟩ := ha
  ext <;> simp only [vec] <;> first | rfl | assumption

/-- **The fundamental identity `a b = a·b + a∧b`, for arbitrary vectors** (Hestenes' defining relation,
    not tied to coordinate literals): for any grade-1 `a`, `b`, the geometric product splits into its
    scalar (inner) part `a·b` and its bivector (outer) part `a∧b`. The master rewrite that turns a
    geometric product of vectors into inner + outer, coordinate-free at the call site. -/
theorem mul_eq_dot_add_wedge {a b : G3} (ha : IsVector a) (hb : IsVector b) :
    mul a b = add (smul (dot a b) one) (wedge a b) := by
  obtain ⟨_, ha12, ha13, ha23, ha123⟩ := ha
  obtain ⟨hbs, hb12, hb13, hb23, hb123⟩ := hb
  simp only [mul, wedge, smul, one, dot, add]
  ext <;> simp only [ha12, ha13, ha23, ha123, hbs, hb12, hb13, hb23, hb123] <;> ring

/-- **Orthogonal vectors' geometric product is their wedge** (arbitrary vectors): `a·b = 0 ⟹ a b = a∧b`.
    The general-`IsVector` form of `vec_mul_perp`, a corollary of the split. -/
theorem mul_eq_wedge_of_perp {a b : G3} (ha : IsVector a) (hb : IsVector b) (h : dot a b = 0) :
    mul a b = wedge a b := by
  rw [mul_eq_dot_add_wedge ha hb, h]
  simp only [smul, one, add]; ext <;> ring

/-- A coordinate vector is grade-1. -/
theorem isVector_vec (x y z : ℝ) : IsVector (vec x y z) := ⟨rfl, rfl, rfl, rfl, rfl⟩

/-- `B` is a **bivector** (grade 2): its scalar, vector and pseudoscalar parts vanish — how "`B` is a
    (simple, in 𝒢₃ always simple) bivector" is stated for an arbitrary `B : G3`. The plane companion of
    `IsVector`. -/
def IsBivector (B : G3) : Prop := B.s = 0 ∧ B.c1 = 0 ∧ B.c2 = 0 ∧ B.c3 = 0 ∧ B.c123 = 0

/-- A grade-2 multivector is the `bivector` of its own grade-2 coordinates — the bridge to the
    `bivector …` lemmas (the `eq_vec_of_isVector` analogue for planes). -/
theorem eq_bivector_of_isBivector {B : G3} (hB : IsBivector B) : B = bivector B.c12 B.c13 B.c23 := by
  obtain ⟨hs, h1, h2, h3, h123⟩ := hB
  ext <;> simp only [bivector, zero] <;> first | rfl | assumption

/-- A coordinate `bivector p q r` is grade-2 — lets a caller discharge the `IsBivector` hypothesis of an
    object-level theorem when it holds a concrete `bivector`. -/
theorem isBivector_bivector (p q r : ℝ) : IsBivector (bivector p q r) :=
  ⟨rfl, rfl, rfl, rfl, rfl⟩

/-- `T` is a **trivector** (the pseudoscalar, grade 3): every part but `e₁₂₃` vanishes. The grade-3
    companion of `IsVector`/`IsBivector`. -/
def IsTrivector (T : G3) : Prop :=
  T.s = 0 ∧ T.c1 = 0 ∧ T.c2 = 0 ∧ T.c3 = 0 ∧ T.c12 = 0 ∧ T.c13 = 0 ∧ T.c23 = 0

/-- A grade-3 multivector is the `trivector` of its own pseudoscalar coordinate — the bridge to the
    `trivector …` lemmas. -/
theorem eq_trivector_of_isTrivector {T : G3} (hT : IsTrivector T) : T = trivector T.c123 := by
  obtain ⟨hs, h1, h2, h3, h12, h13, h23⟩ := hT
  ext <;> simp only [trivector, zero] <;> first | rfl | assumption

/-- A coordinate `trivector t` is grade-3. -/
theorem isTrivector_trivector (t : ℝ) : IsTrivector (trivector t) :=
  ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-- Grade-1 is closed under scalar multiplication. -/
theorem IsVector.smul {a : G3} (ha : IsVector a) (k : ℝ) : IsVector (GacalcProofs.G3.smul k a) := by
  obtain ⟨hs, h12, h13, h23, h123⟩ := ha
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> simp [GacalcProofs.G3.smul, hs, h12, h13, h23, h123]

/-- Grade-1 is closed under subtraction. -/
theorem IsVector.sub {a b : G3} (ha : IsVector a) (hb : IsVector b) : IsVector (GacalcProofs.G3.sub a b) := by
  obtain ⟨has, ha12, ha13, ha23, ha123⟩ := ha
  obtain ⟨hbs, hb12, hb13, hb23, hb123⟩ := hb
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;>
    simp [GacalcProofs.G3.sub, has, ha12, ha13, ha23, ha123, hbs, hb12, hb13, hb23, hb123]

/-- `reverse` fixes a vector (it only flips the sign of grades 2 and 3, which a vector lacks). -/
theorem reverse_vec (x y z : ℝ) : reverse (vec x y z) = vec x y z := by
  simp only [reverse, vec]; ext <;> ring

/-! ### Inner/outer-product properties (leaf lemmas — the coordinate bridge) -/

/-- **The scalar product is symmetric:** `a·b = b·a` (the scalar part of a product is symmetric). -/
theorem dot_comm (a b : G3) : dot a b = dot b a := by simp only [dot, mul]; ring

/-- `dot` distributes over addition on the left. -/
theorem dot_add_left (u w v : G3) : dot (add u w) v = dot u v + dot w v := by
  simp only [dot, mul, add]; ring

/-- **Leaf:** the dot product on coordinate vectors is the Euclidean dot `a₁ * b₁ + a₂ * b₂ + a₃ * b₃`. Reuse
    this named lemma instead of re-deriving it inline. -/
theorem dot_vec (a1 a2 a3 b1 b2 b3 : ℝ) :
    dot (vec a1 a2 a3) (vec b1 b2 b3) = a1 * b1 + a2 * b2 + a3 * b3 := by
  simp only [dot, mul, vec]; ring

/-- The **squared magnitude** `|A|² = ⟨A Ã⟩₀` (Hestenes & Sobczyk p.13 eq 1.49, gacalc
    `magnitude_squared`; `⟨AÃ⟩ = ⟨ÃA⟩` as the scalar part is symmetric). -/
noncomputable def normSq (a : G3) : ℝ := (mul a (reverse a)).s

/-- The **magnitude** `|A| = √⟨A Ã⟩` (Hestenes p.13 eq 1.49, gacalc `magnitude`), for all grades. -/
noncomputable def magnitude (a : G3) : ℝ := Real.sqrt (normSq a)

/-- `normSq a = Σ (component)²` — the scalar part of `a ã` is positive-definite (every blade's reverse
    sign cancels its square's sign). -/
theorem normSq_eq_sum_sq (a : G3) : normSq a = a.s ^ 2 + a.c1 ^ 2 + a.c2 ^ 2 + a.c3 ^ 2 + a.c12 ^ 2 + a.c13 ^ 2 + a.c23 ^ 2 + a.c123 ^ 2 := by
  simp only [normSq, mul, reverse]; ring

theorem normSq_nonneg (a : G3) : 0 ≤ normSq a := by
  rw [normSq_eq_sum_sq]; positivity

/-- `|a|² = normSq a` for ANY multivector — the one `√` fact the magnitude tier needs. -/
theorem magnitude_sq_eq_normSq (a : G3) : magnitude a ^ 2 = normSq a := by
  simp only [magnitude]; exact Real.sq_sqrt (normSq_nonneg a)

theorem magnitude_ne_zero_of_normSq_ne_zero {a : G3} (h : normSq a ≠ 0) : magnitude a ≠ 0 := by
  simp only [magnitude]
  exact Real.sqrt_ne_zero'.mpr (lt_of_le_of_ne (normSq_nonneg a) (Ne.symm h))

/-- **Leaf:** `|a|² = a₁² + a₂² + a₃²` on a coordinate vector. -/
theorem normSq_vec (a1 a2 a3 : ℝ) : normSq (vec a1 a2 a3) = a1 ^ 2 + a2 ^ 2 + a3 ^ 2 := by
  simp only [normSq, mul, reverse, vec]; ring

/-- **Leaf — self-dot IS the squared magnitude, on a vector:** `a·a = |a|²`. The formal statement of
    "a vector dotted with itself is its magnitude squared"; the bridge that lets a `dot a a` hypothesis
    be read as the primitive `normSq a` (`reverse` fixes a vector, so `⟨a a⟩ = ⟨a ã⟩`). Reuse instead of
    re-deriving `rw [dot_vec, normSq_vec]; ring` inline. -/
theorem dot_self_vec_eq_normSq_coord (a1 a2 a3 : ℝ) :
    dot (vec a1 a2 a3) (vec a1 a2 a3) = normSq (vec a1 a2 a3) := by
  rw [dot_vec, normSq_vec]; ring

/-- **Leaf:** the wedge of two coordinate vectors is the plane bivector, in coordinates:
    `a ∧ b = (a₁ * b₂−a₂ * b₁)e₁₂ + (a₁ * b₃−a₃ * b₁)e₁₃ + (a₂ * b₃−a₃ * b₂)e₂₃`. Reuse instead of re-deriving the literal
    with `simp only [wedge, vec]; ext <;> ring` inline. -/
theorem wedge_vec_eq_biv (a1 a2 a3 b1 b2 b3 : ℝ) :
    wedge (vec a1 a2 a3) (vec b1 b2 b3)
      = bivector (a1 * b2 - a2 * b1) (a1 * b3 - a3 * b1) (a2 * b3 - a3 * b2) := by
  simp only [wedge, vec, bivector, zero]; ext <;> ring

/-- **A vector's square is its squared magnitude:** `a a = |a|² * 1` (`a∧a = 0`, so only the scalar
    survives). The `B B = |B|²` half of the blade-inverse identity. -/
theorem mul_vec_self_coord (a1 a2 a3 : ℝ) :
    mul (vec a1 a2 a3) (vec a1 a2 a3) = smul (normSq (vec a1 a2 a3)) one := by
  rw [normSq_vec]; simp only [mul, one, smul, vec]; ext <;> ring

/-- **Leaf:** `|a∧b|² = (a₁ * b₂−a₂ * b₁)² + (a₁ * b₃−a₃ * b₁)² + (a₂ * b₃−a₃ * b₂)²`. -/
theorem normSq_wedge_vec (a1 a2 a3 b1 b2 b3 : ℝ) :
    normSq (wedge (vec a1 a2 a3) (vec b1 b2 b3))
      = (a1 * b2 - a2 * b1) ^ 2 + (a1 * b3 - a3 * b1) ^ 2 + (a2 * b3 - a3 * b2) ^ 2 := by
  simp only [normSq, wedge, mul, reverse, vec]; ring

/-- **The wedge of vectors is antisymmetric:** `a∧b = −(b∧a)`. -/
theorem wedge_antisymm {a b : G3} (ha : IsVector a) (hb : IsVector b) :
    wedge a b = neg (wedge b a) := by
  rw [eq_vec_of_isVector ha, eq_vec_of_isVector hb]
  simp only [wedge, vec, neg]; ext <;> ring

/-- The wedge distributes over subtraction on the left. -/
theorem wedge_sub_left (u w a : G3) : wedge (sub u w) a = sub (wedge u a) (wedge w a) := by
  simp only [wedge, sub]; ext <;> ring

/-- The wedge pulls out a scalar on the left. -/
theorem wedge_smul_left (k : ℝ) (u a : G3) : wedge (smul k u) a = smul k (wedge u a) := by
  simp only [wedge, smul]; ext <;> ring

/-- The wedge distributes over addition on the left. -/
theorem wedge_add_left (u w a : G3) : wedge (add u w) a = add (wedge u a) (wedge w a) := by
  simp only [wedge, add]; ext <;> ring

/-- The inverse unit pseudoscalar I₃⁻¹ = −e₁₂₃ (since I₃² = −1). -/
def I_inv : G3 := ⟨0, 0, 0, 0, 0, 0, 0, -1⟩

/-- I₃ · I₃⁻¹ = 1. -/
theorem I_mul_I_inv : mul I I_inv = one := by
  simp only [mul, I, e_123, I_inv, one]; ext <;> ring

/-- The dual `A* = A · I₃⁻¹` (grade r ↦ grade 3−r), matching gacalc's `dual`
    (base.py). In 3D, `dual (a ∧ b)` is the plane normal (gacalc's `cross a b`). -/
noncomputable def dual (a : G3) : G3 := mul a I_inv

/-! ### The self-product vector leaves, object form (compute on the vector's own getters) -/

/-- `a ∧ a = 0` for a vector `a`. -/
theorem wedge_self_vec {a : G3} (ha : IsVector a) : wedge a a = zero := by
  obtain ⟨has, ha12, ha13, ha23, _⟩ := ha
  simp only [wedge, zero, has, ha12, ha13, ha23]
  ext <;> ring

/-- `a · a = |a|²` for a vector `a`. -/
theorem dot_self_vec_eq_normSq {a : G3} (ha : IsVector a) : dot a a = normSq a := by
  obtain ⟨_, ha12, ha13, ha23, ha123⟩ := ha
  simp only [dot, normSq, mul, reverse, ha12, ha13, ha23, ha123]
  ring

/-- `a a = |a|² * 1` for a vector `a`. -/
theorem mul_vec_self {a : G3} (ha : IsVector a) : mul a a = smul (normSq a) one := by
  obtain ⟨has, ha12, ha13, ha23, ha123⟩ := ha
  simp only [normSq, mul, reverse, one, smul, has, ha12, ha13, ha23, ha123]
  ext <;> ring

/-! ### Dot and wedge as the two parts of the geometric product (3D) -/

/-- **The dot product is the symmetric part of the geometric product** (3D): `½(ab + ba) = (a·b) * 1`
    for vectors — the 3D twin of `G2.dot_is_sym_part`, in object form. -/
theorem dot_is_sym_part {a b : G3} (ha : IsVector a) (hb : IsVector b) :
    smul (1 / 2) (add (mul a b) (mul b a)) = smul (dot a b) one := by
  obtain ⟨has, ha12, ha13, ha23, ha123⟩ := ha
  obtain ⟨hbs, hb12, hb13, hb23, hb123⟩ := hb
  simp only [smul, add, mul, dot, one, has, ha12, ha13, ha23, ha123, hbs, hb12, hb13, hb23, hb123]
  ext <;> ring

/-- **The wedge product is the antisymmetric part of the geometric product** (3D): `½(ab − ba) = a∧b`
    for vectors — the 3D twin of `G2.wedge_is_antisym_part`, in object form. -/
theorem wedge_is_antisym_part {a b : G3} (ha : IsVector a) (hb : IsVector b) :
    smul (1 / 2) (sub (mul a b) (mul b a)) = wedge a b := by
  obtain ⟨has, ha12, ha13, ha23, ha123⟩ := ha
  obtain ⟨hbs, hb12, hb13, hb23, hb123⟩ := hb
  simp only [smul, sub, mul, wedge, has, ha12, ha13, ha23, ha123, hbs, hb12, hb13, hb23, hb123]
  ext <;> ring

/-- `I₃² = (−1)^(r(r−1)/2)` with `r = 3`: the 3D case of the general sign formula
    (`tasks/reference/pseudoscalar-square-sign.md`), read off `I_sq`. -/
theorem I_sq_eq_sign : (mul I I).s = (-1 : ℝ) ^ (3 * (3 - 1) / 2) := by
  simp only [mul, I, e_123]; norm_num

end G3

end GacalcProofs
