import Mathlib

/-! # 𝒢₃ from scratch: the 8-dimensional Euclidean geometric algebra

    A self-contained construction of the 3D geometric algebra over ℝ in the basis
    {1, e₁, e₂, e₃, e₁e₂, e₁e₃, e₂e₃, e₁e₂e₃}, Euclidean signature (eᵢ²=1, eᵢeⱼ=−eⱼeᵢ).
    Built the same way as `G2`: a coordinate struct whose fields are the eight real
    **coefficients**, with the basis blades exposed as genuine `G3` **elements**
    (`one`/`e_1`/…/`e_123`) — a basis vector is a vector, not a real.

    The shared prerequisite for the 3D proofs (projection, dot, wedge, pseudoscalar,
    the rotation sandwich) — see `tasks/reference/lean-ga-proof-architecture.md` and the umbrella
    `tasks/investigate-lean-proofs-for-ga.md`.

    **The geometric product / wedge / reverse formulas are NOT hand-derived** — they were
    generated by running gacalc's reference `Gn` on two fully-symbolic 3D multivectors and
    transcribed verbatim (`tools/derive_lean_algebra.py`), so the product
    is correct-by-construction against gacalc, the oracle. The multiplication-table lemmas
    below (`e_1_sq`, `e_1_mul_e_2`, the anticommutation, `I_sq`) then independently confirm
    the transcription. -/
namespace GacalcProofs

/-- An element of 𝒢₃, stored by its eight real coefficients on the basis blades. The
    fields are coefficients (reals); the basis blades are the elements `one`/`e_1`/…/`e_123`
    below. `@[ext]` gives componentwise extensionality for the `ext` tactic. -/
@[ext]
structure G3 where
  s : ℝ    -- coefficient of the scalar unit 1      (grade 0)
  c1 : ℝ   -- coefficient of e₁                       (grade 1)
  c2 : ℝ   -- coefficient of e₂                       (grade 1)
  c3 : ℝ   -- coefficient of e₃                       (grade 1)
  c12 : ℝ  -- coefficient of e₁e₂                     (grade 2)
  c13 : ℝ  -- coefficient of e₁e₃                     (grade 2)
  c23 : ℝ  -- coefficient of e₂e₃                     (grade 2)
  c123 : ℝ -- coefficient of e₁e₂e₃ (pseudoscalar)    (grade 3)

namespace G3

/-- The Euclidean geometric product in 𝒢₃ (transcribed from gacalc's `Gn` via
    `tools/derive_lean_algebra.py`). `noncomputable` (ℝ field ops). -/
noncomputable def mul (a b : G3) : G3 where
  s :=
    a.c1 * b.c1 - a.c12 * b.c12 - a.c123 * b.c123 - a.c13 * b.c13 + a.c2 * b.c2
      - a.c23 * b.c23 + a.c3 * b.c3 + a.s * b.s
  c1 :=
    a.c1 * b.s + a.c12 * b.c2 - a.c123 * b.c23 + a.c13 * b.c3 - a.c2 * b.c12
      - a.c23 * b.c123 - a.c3 * b.c13 + a.s * b.c1
  c2 :=
    a.c1 * b.c12 - a.c12 * b.c1 + a.c123 * b.c13 + a.c13 * b.c123 + a.c2 * b.s
      + a.c23 * b.c3 - a.c3 * b.c23 + a.s * b.c2
  c3 :=
    a.c1 * b.c13 - a.c12 * b.c123 - a.c123 * b.c12 - a.c13 * b.c1 + a.c2 * b.c23
      - a.c23 * b.c2 + a.c3 * b.s + a.s * b.c3
  c12 :=
    a.c1 * b.c2 + a.c12 * b.s + a.c123 * b.c3 - a.c13 * b.c23 - a.c2 * b.c1
      + a.c23 * b.c13 + a.c3 * b.c123 + a.s * b.c12
  c13 :=
    a.c1 * b.c3 + a.c12 * b.c23 - a.c123 * b.c2 + a.c13 * b.s - a.c2 * b.c123
      - a.c23 * b.c12 - a.c3 * b.c1 + a.s * b.c13
  c23 :=
    a.c1 * b.c123 - a.c12 * b.c13 + a.c123 * b.c1 + a.c13 * b.c12 + a.c2 * b.c3
      + a.c23 * b.s - a.c3 * b.c2 + a.s * b.c23
  c123 :=
    a.c1 * b.c23 + a.c12 * b.c3 + a.c123 * b.s - a.c13 * b.c2 - a.c2 * b.c13
      + a.c23 * b.c1 + a.c3 * b.c12 + a.s * b.c123

/-- The outer (wedge) product in 𝒢₃ (also transcribed from gacalc's `Gn`). -/
noncomputable def wedge (a b : G3) : G3 where
  s := a.s * b.s
  c1 := a.c1 * b.s + a.s * b.c1
  c2 := a.c2 * b.s + a.s * b.c2
  c3 := a.c3 * b.s + a.s * b.c3
  c12 := a.c1 * b.c2 + a.c12 * b.s - a.c2 * b.c1 + a.s * b.c12
  c13 := a.c1 * b.c3 + a.c13 * b.s - a.c3 * b.c1 + a.s * b.c13
  c23 := a.c2 * b.c3 + a.c23 * b.s - a.c3 * b.c2 + a.s * b.c23
  c123 :=
    a.c1 * b.c23 + a.c12 * b.c3 + a.c123 * b.s - a.c13 * b.c2 - a.c2 * b.c13
      + a.c23 * b.c1 + a.c3 * b.c12 + a.s * b.c123

/-- Componentwise addition. -/
noncomputable def add (a b : G3) : G3 :=
  ⟨a.s + b.s, a.c1 + b.c1, a.c2 + b.c2, a.c3 + b.c3,
   a.c12 + b.c12, a.c13 + b.c13, a.c23 + b.c23, a.c123 + b.c123⟩

/-- Componentwise subtraction. -/
noncomputable def sub (a b : G3) : G3 :=
  ⟨a.s - b.s, a.c1 - b.c1, a.c2 - b.c2, a.c3 - b.c3,
   a.c12 - b.c12, a.c13 - b.c13, a.c23 - b.c23, a.c123 - b.c123⟩

/-- Componentwise negation. -/
noncomputable def neg (a : G3) : G3 :=
  ⟨-a.s, -a.c1, -a.c2, -a.c3, -a.c12, -a.c13, -a.c23, -a.c123⟩

/-- Scalar multiple. -/
noncomputable def smul (r : ℝ) (a : G3) : G3 :=
  ⟨r * a.s, r * a.c1, r * a.c2, r * a.c3,
   r * a.c12, r * a.c13, r * a.c23, r * a.c123⟩

/-- Reverse `R̃` — grade sign (−1)^(k(k−1)/2): grades 0,1 fixed, grades 2,3 negated
    (transcribed from gacalc; matches the G2 reverse pattern extended to grade 3). -/
noncomputable def reverse (a : G3) : G3 :=
  ⟨a.s, a.c1, a.c2, a.c3, -a.c12, -a.c13, -a.c23, -a.c123⟩

/-! ### Basis blades as genuine `G3` elements -/

def one : G3 := ⟨1, 0, 0, 0, 0, 0, 0, 0⟩
def e_1 : G3 := ⟨0, 1, 0, 0, 0, 0, 0, 0⟩
def e_2 : G3 := ⟨0, 0, 1, 0, 0, 0, 0, 0⟩
def e_3 : G3 := ⟨0, 0, 0, 1, 0, 0, 0, 0⟩
def e_12 : G3 := ⟨0, 0, 0, 0, 1, 0, 0, 0⟩
def e_13 : G3 := ⟨0, 0, 0, 0, 0, 1, 0, 0⟩
def e_23 : G3 := ⟨0, 0, 0, 0, 0, 0, 1, 0⟩
def e_123 : G3 := ⟨0, 0, 0, 0, 0, 0, 0, 1⟩

/-- A grade-1 vector from its three coordinates. -/
def vec (x y z : ℝ) : G3 := ⟨0, x, y, z, 0, 0, 0, 0⟩

/-- The unit pseudoscalar I₃ = e₁e₂e₃. -/
def I : G3 := e_123

/-! ### The geometric-product multiplication table (confirms the transcription) -/

theorem e_1_sq : mul e_1 e_1 = one := by simp only [mul, e_1, one]; ext <;> ring
theorem e_2_sq : mul e_2 e_2 = one := by simp only [mul, e_2, one]; ext <;> ring
theorem e_3_sq : mul e_3 e_3 = one := by simp only [mul, e_3, one]; ext <;> ring

/-- e₁e₂ = e₁₂ (the bivector is the product of the two basis vectors). -/
theorem e_1_mul_e_2 : mul e_1 e_2 = e_12 := by simp only [mul, e_1, e_2, e_12]; ext <;> ring
theorem e_1_mul_e_3 : mul e_1 e_3 = e_13 := by simp only [mul, e_1, e_3, e_13]; ext <;> ring
theorem e_2_mul_e_3 : mul e_2 e_3 = e_23 := by simp only [mul, e_2, e_3, e_23]; ext <;> ring

/-- e₂e₁ = −e₁₂ (orthogonal basis vectors anticommute). -/
theorem e_2_mul_e_1 : mul e_2 e_1 = neg e_12 := by
  simp only [mul, e_2, e_1, e_12, neg]; ext <;> ring

/-- e₁e₂e₃ = e₁₂₃ (the pseudoscalar is the product of the three basis vectors). -/
theorem e_12_mul_e_3 : mul e_12 e_3 = e_123 := by
  simp only [mul, e_12, e_3, e_123]; ext <;> ring

/-- **The pseudoscalar squares to −1:** I₃² = −1 = (−1)^(3·2/2). -/
theorem I_sq : mul I I = neg one := by simp only [mul, I, e_123, neg, one]; ext <;> ring

/-- Reverse is an involution. -/
theorem reverse_reverse (a : G3) : reverse (reverse a) = a := by
  simp only [reverse]; ext <;> ring

/-! ### The dual, the dot, and bilinearity helpers (for projection) -/

/-- The zero multivector. -/
def zero : G3 := ⟨0, 0, 0, 0, 0, 0, 0, 0⟩

/-- The scalar product ⟨A B⟩₀ — the scalar part of the geometric product. For two
    vectors this is the Euclidean dot product `a₁b₁ + a₂b₂ + a₃b₃`. -/
noncomputable def dot (a b : G3) : ℝ := (mul a b).s

/-- `dot` distributes over subtraction on the left (it is bilinear). -/
theorem dot_sub_left (u w v : G3) : dot (sub u w) v = dot u v - dot w v := by
  simp only [dot, mul, sub]; ring

/-- `dot` pulls out a scalar on the left. -/
theorem dot_smul_left (k : ℝ) (u v : G3) : dot (smul k u) v = k * dot u v := by
  simp only [dot, mul, smul]; ring

/-- The wedge distributes over subtraction on the right. -/
theorem wedge_sub_right (a u w : G3) : wedge a (sub u w) = sub (wedge a u) (wedge a w) := by
  simp only [wedge, sub]; ext <;> ring

/-- The wedge pulls out a scalar on the right. -/
theorem wedge_smul_right (k : ℝ) (a u : G3) : wedge a (smul k u) = smul k (wedge a u) := by
  simp only [wedge, smul]; ext <;> ring

/-- A vector wedged with itself is zero. -/
theorem wedge_self_vec (x y z : ℝ) : wedge (vec x y z) (vec x y z) = zero := by
  simp only [wedge, vec, zero]; ext <;> ring

/-- **The fundamental identity `a b = a·b + a∧b` for vectors** (Hestenes' defining relation):
    the geometric product of two vectors splits into its scalar (inner) part `a·b` and its
    bivector (outer) part `a∧b`. Unconditional; pure `ring`. -/
theorem vec_mul_eq_dot_add_wedge (a1 a2 a3 b1 b2 b3 : ℝ) :
    mul (vec a1 a2 a3) (vec b1 b2 b3)
      = add (smul (dot (vec a1 a2 a3) (vec b1 b2 b3)) one)
            (wedge (vec a1 a2 a3) (vec b1 b2 b3)) := by
  simp only [mul, wedge, smul, one, dot, add, vec]; ext <;> ring

/-- **Orthogonal vectors' geometric product is their wedge:** for vectors with `a · b = 0`,
    `a b = a ∧ b`. A corollary of the fundamental identity — orthogonality kills the scalar part,
    leaving only the bivector. This is what turns `a (b − proj_a b)` into the plane bivector
    `a ∧ b` (with `r = b − proj_a b ⊥ a`) — the step that reduces the 3D versor sandwich to 2D. -/
theorem vec_mul_perp (a1 a2 a3 b1 b2 b3 : ℝ)
    (h : dot (vec a1 a2 a3) (vec b1 b2 b3) = 0) :
    mul (vec a1 a2 a3) (vec b1 b2 b3) = wedge (vec a1 a2 a3) (vec b1 b2 b3) := by
  rw [vec_mul_eq_dot_add_wedge, h]
  simp only [smul, one, add, zero]; ext <;> ring

/-- The inverse unit pseudoscalar I₃⁻¹ = −e₁₂₃ (since I₃² = −1). -/
def I_inv : G3 := ⟨0, 0, 0, 0, 0, 0, 0, -1⟩

/-- I₃ · I₃⁻¹ = 1. -/
theorem I_mul_I_inv : mul I I_inv = one := by
  simp only [mul, I, e_123, I_inv, one]; ext <;> ring

/-- The dual `A* = A · I₃⁻¹` (grade r ↦ grade 3−r), matching gacalc's `dual`
    (base.py:1217). In 3D, `dual (a ∧ b)` is the plane normal (gacalc's `cross a b`). -/
noncomputable def dual (a : G3) : G3 := mul a I_inv

end G3

end GacalcProofs
