import GacalcProofs.Lagrange
import GacalcProofs.G2
import GacalcProofs.G3
import GacalcProofs.AlgebraLaws
import GacalcProofs.Versor2D
import GacalcProofs.Sandwich
import GacalcProofs.RotateComponents
import GacalcProofs.Projection2D
import GacalcProofs.Trig
import GacalcProofs.Projection
import GacalcProofs.Rotation
import GacalcProofs.Rotation3D
import GacalcProofs.StandardPosition
import GacalcProofs.Cross
