# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# AUTO-GENERATED by tools/gen_specialized.py -- do not edit by hand.
# Regenerate with:  python tools/gen_specialized.py
#
# G1: a specialized, performant representation of 𝒢₁ -- a named-field
# dataclass whose geometric product is the closed form derived from the general
# Gn symbolic product.

import dataclasses
import numbers
import typing
from collections.abc import Generator

import numpy as np
import sympy

from geometricalgebra.base import AbstractMultiVector, BladeCoef
from geometricalgebra.gn import Gn


@dataclasses.dataclass(eq=False)
class G1(AbstractMultiVector):
    """An element (multivector) of 𝒢₁, the geometric algebra of the Euclidean
    line ℝ¹ (Hestenes' notation) -- the simplest geometric algebra.

    𝒢₁ has 2¹ = 2 basis blades, stored as named fields:
        scalar          grade 0 (scalar)
        e_1             grade 1 (the lone vector / pseudoscalar)

    A specialized, performant representation of 𝒢₁; see Gn for the general
    𝒢ₙ case.  Terminology: 𝒢₁ denotes the *algebra*; an instance of this
    class is an *element of* 𝒢₁.

    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified
    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."""

    DIMENSION: typing.ClassVar[int] = 1

    scalar: numbers.Real = typing.cast(numbers.Real, 0)
    e_1: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            scalar=typing.cast(numbers.Real, d.get((), 0)),
            e_1=typing.cast(numbers.Real, d.get((1,), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((), self.scalar),
                ((1,), self.e_1),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def _geometric_product(self, rhs) -> typing.Self:
        """
        Geometric product  A B  (juxtaposition) — the fundamental product of the
        algebra, from which the inner product  A · B  and outer product  A ∧ B  are
        derived.  This is the representation-specific primitive.
        """
        if not isinstance(rhs, G1):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left * right)
        result = G1(
            scalar=self.scalar * rhs.scalar + self.e_1 * rhs.e_1,
            e_1=self.scalar * rhs.e_1 + self.e_1 * rhs.scalar,
        )
        return typing.cast(typing.Self, result)

    def inner_product(self, rhs) -> typing.Self:
        """
        Inner (dot) product  A · B  — the lowest-grade part of the geometric
        product, ⟨A B⟩_|r−s| summed over the homogeneous grade-r, grade-s parts.

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 6,
        equation 1.21a, 1.21b, 1.21c
        """
        if not isinstance(rhs, G1):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left.inner_product(right))
        result = G1(
            scalar=self.e_1 * rhs.e_1,
            e_1=typing.cast(numbers.Real, 0),
        )
        return typing.cast(typing.Self, result)

    def outer_product(self, rhs) -> typing.Self:
        """
        Outer (wedge) product  A ∧ B  — the highest-grade part of the geometric
        product, ⟨A B⟩_(r+s) summed over the homogeneous grade-r, grade-s parts.

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 6,
        equation 1.22a, 1.22b, 1.22c
        """
        if not isinstance(rhs, G1):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left.outer_product(right))
        result = G1(
            scalar=self.scalar * rhs.scalar,
            e_1=self.scalar * rhs.e_1 + self.e_1 * rhs.scalar,
        )
        return typing.cast(typing.Self, result)

    def __add__(self, rhs) -> typing.Self:
        if not isinstance(rhs, G1):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left + right)
        result = G1(
            scalar=self.scalar + rhs.scalar,
            e_1=self.e_1 + rhs.e_1,
        )
        return typing.cast(typing.Self, result)

    def __sub__(self, rhs) -> typing.Self:
        if not isinstance(rhs, G1):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left - right)
        result = G1(
            scalar=self.scalar - rhs.scalar,
            e_1=self.e_1 - rhs.e_1,
        )
        return typing.cast(typing.Self, result)

    def __neg__(self) -> typing.Self:
        result = G1(
            scalar=typing.cast(numbers.Real, -self.scalar),
            e_1=typing.cast(numbers.Real, -self.e_1),
        )
        return typing.cast(typing.Self, result)

    def scalar_part(self) -> numbers.Real:
        """
        Scalar part  ⟨A⟩  =  ⟨A⟩₀  — the grade-0 (scalar) component of A.

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 4
        """
        return self.scalar

    def grades(self) -> list[int]:
        present: list[int] = []
        if self.scalar != 0:
            present.append(0)
        if self.e_1 != 0:
            present.append(1)
        return present

    def r_vector_part(self, r: int) -> typing.Self:
        """
        Grade-r part  ⟨A⟩ᵣ  — the r-vector (grade-r) component of A.

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 4
        """
        if r == 0:
            result = G1(
                scalar=self.scalar,
            )
            return typing.cast(typing.Self, result)
        if r == 1:
            result = G1(
                e_1=self.e_1,
            )
            return typing.cast(typing.Self, result)
        result = G1()
        return typing.cast(typing.Self, result)

    def reverse(self) -> typing.Self:
        """
        Reverse  Ã  — reverses the order of the vector factors in each blade,
        giving the grade-r part the sign (−1)^(r(r−1)/2).

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 5,
        equation 1.19
        """
        result = G1(
            scalar=self.scalar,
            e_1=self.e_1,
        )
        return typing.cast(typing.Self, result)

    def even_part(self) -> typing.Self:
        """
        Even part  A⁺  =  ⟨A⟩₀ + ⟨A⟩₂ + …  — the sum of the even-grade parts.

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 8
        """
        result = G1(
            scalar=self.scalar,
        )
        return typing.cast(typing.Self, result)

    def odd_part(self) -> typing.Self:
        """
        Odd part  A⁻  =  ⟨A⟩₁ + ⟨A⟩₃ + …  — the sum of the odd-grade parts.

        from Hestenes and Sobczyk, Clifford Algebra to Geometric Calculus, page 8
        """
        result = G1(
            e_1=self.e_1,
        )
        return typing.cast(typing.Self, result)

    def is_close(self, other) -> bool:
        if not isinstance(other, G1):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.scalar), float(other.scalar), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_1), float(other.e_1), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.scalar != 0:
            yield G1(scalar=self.scalar)
        if self.e_1 != 0:
            yield G1(e_1=self.e_1)

    def dual(self, n: int | None = None) -> typing.Self:
        """
        Dual  A*  =  A I⁻¹  — multiplication by the inverse unit pseudoscalar I,
        mapping a grade-r part to grade n−r.
        """
        return super().dual(self.DIMENSION if n is None else n)

    @classmethod
    def unit_pseudoscalar(cls, n: int | None = None) -> typing.Self:
        """
        Unit pseudoscalar  i  =  e₁ e₂ … e_n  — the highest-grade unit blade of
        the n-dimensional algebra.
        """
        return super().unit_pseudoscalar(cls.DIMENSION if n is None else n)

    @classmethod
    def unit_pseudoscalar_squared(cls, n: int | None = None) -> typing.Self:
        return super().unit_pseudoscalar_squared(cls.DIMENSION if n is None else n)

    @classmethod
    def bases(cls, n: int | None = None) -> Generator[typing.Self]:
        return super().bases(cls.DIMENSION if n is None else n)

    @classmethod
    def symbolic_multivector(
        cls, n: int | None = None, prefix: str = "a"
    ) -> typing.Self:
        return super().symbolic_multivector(cls.DIMENSION if n is None else n, prefix)


zero: G1 = G1.from_scalar(0)
one: G1 = G1.from_scalar(1)
e_1: G1 = G1.from_blade_dict({(1,): 1})

__all__ = ["G1", "zero", "one", "e_1"]
