# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# AUTO-GENERATED by tools/gen_specialized.py -- do not edit by hand.
# Regenerate with:  python tools/gen_specialized.py
#
# G1: a specialized, performant representation of 𝒢₁ -- a named-field
# dataclass whose geometric product is the closed form derived from the general
# Gn symbolic product.

import dataclasses
import numbers
import typing

import sympy

from geometricalgebra.base import AbstractMultiVector, BladeCoef
from geometricalgebra.gn import Gn


@dataclasses.dataclass(eq=False)
class G1(AbstractMultiVector):
    """An element (multivector) of 𝒢₁, the geometric algebra of the Euclidean
    line ℝ¹ (Hestenes' notation) -- the simplest geometric algebra.

    𝒢₁ has 2¹ = 2 basis blades, stored as named fields:
        scalar          grade 0 (scalar)
        e_1             grade 1 (the lone vector / pseudoscalar)

    A specialized, performant representation of 𝒢₁; see Gn for the general
    𝒢ₙ case.  Terminology: 𝒢₁ denotes the *algebra*; an instance of this
    class is an *element of* 𝒢₁.

    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified
    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."""

    scalar: numbers.Real = typing.cast(numbers.Real, 0)
    e_1: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            scalar=typing.cast(numbers.Real, d.get((), 0)),
            e_1=typing.cast(numbers.Real, d.get((1,), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((), self.scalar),
                ((1,), self.e_1),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def _geometric_product(self, rhs) -> typing.Self:
        if not isinstance(rhs, G1):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left * right)
        result = G1(
            scalar=self.e_1*rhs.e_1 + self.scalar*rhs.scalar,
            e_1=self.e_1*rhs.scalar + self.scalar*rhs.e_1,
        )
        return typing.cast(typing.Self, result)
