# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# AUTO-GENERATED by tools/gen_specialized.py -- do not edit by hand.
# Regenerate with:  python tools/gen_specialized.py
#
# G2: a specialized, performant representation of 𝒢₂ -- a named-field
# dataclass whose geometric product is the closed form derived from the general
# Gn symbolic product.

import dataclasses
import numbers
import typing

import sympy

from geometricalgebra.base import AbstractMultiVector, BladeCoef
from geometricalgebra.gn import Gn


@dataclasses.dataclass(eq=False)
class G2(AbstractMultiVector):
    """An element (multivector) of 𝒢₂, the geometric algebra of the Euclidean
    plane ℝ² (Hestenes' notation).

    𝒢₂ has 2² = 4 basis blades, stored as named fields:
        scalar          grade 0 (scalar)
        e_1, e_2        grade 1 (vectors)
        e_12            grade 2 (bivector / pseudoscalar)

    A specialized, performant representation of 𝒢₂; see Gn for the general
    𝒢ₙ case.  Terminology: 𝒢₂ denotes the *algebra*; an instance of this
    class is an *element of* 𝒢₂.

    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified
    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."""

    scalar: numbers.Real = typing.cast(numbers.Real, 0)
    e_1: numbers.Real = typing.cast(numbers.Real, 0)
    e_2: numbers.Real = typing.cast(numbers.Real, 0)
    e_12: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            scalar=typing.cast(numbers.Real, d.get((), 0)),
            e_1=typing.cast(numbers.Real, d.get((1,), 0)),
            e_2=typing.cast(numbers.Real, d.get((2,), 0)),
            e_12=typing.cast(numbers.Real, d.get((1, 2), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((), self.scalar),
                ((1,), self.e_1),
                ((2,), self.e_2),
                ((1, 2), self.e_12),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def _geometric_product(self, rhs) -> typing.Self:
        if not isinstance(rhs, G2):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left * right)
        result = G2(
            scalar=(
                self.e_1*rhs.e_1
                - self.e_12*rhs.e_12
                + self.e_2*rhs.e_2
                + self.scalar*rhs.scalar
            ),
            e_1=(
                self.e_1*rhs.scalar
                + self.e_12*rhs.e_2
                - self.e_2*rhs.e_12
                + self.scalar*rhs.e_1
            ),
            e_2=(
                self.e_1*rhs.e_12
                - self.e_12*rhs.e_1
                + self.e_2*rhs.scalar
                + self.scalar*rhs.e_2
            ),
            e_12=(
                self.e_1*rhs.e_2
                + self.e_12*rhs.scalar
                - self.e_2*rhs.e_1
                + self.scalar*rhs.e_12
            ),
        )
        return typing.cast(typing.Self, result)
