# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# AUTO-GENERATED by tools/gen_specialized.py -- do not edit by hand.
# Regenerate with:  python tools/gen_specialized.py
#
# G3: a specialized, performant representation of 𝒢₃ -- a named-field
# dataclass whose geometric product is the closed form derived from the general
# Gn symbolic product.

import dataclasses
import numbers
import typing
from collections.abc import Generator

import numpy as np
import sympy

from geometricalgebra.base import AbstractMultiVector, BladeCoef
from geometricalgebra.gn import Gn
from geometricalgebra.scalar import Scalar


def _coerce(x, cls):
    """Coerce a scalar / any multivector to ``cls`` (the dimension's full type)."""
    if isinstance(x, AbstractMultiVector):
        return cls.from_blade_dict(x.to_blade_dict())
    if isinstance(x, sympy.Expr):
        return cls.from_sympy_expr(x)
    return cls.from_scalar(x)


@dataclasses.dataclass(eq=False)
class G3(AbstractMultiVector):
    """An element (multivector) of 𝒢₃, the geometric algebra of 3D Euclidean
    space ℝ³ (Hestenes' "algebra of physical space"; the Pauli algebra).

    𝒢₃ has 2³ = 8 basis blades, stored as named fields:
        scalar                  grade 0 (scalar)
        e_1, e_2, e_3           grade 1 (vectors)
        e_12, e_13, e_23        grade 2 (bivectors)
        e_123                   grade 3 (trivector / pseudoscalar)

    A specialized, performant representation of 𝒢₃; see Gn for the general
    𝒢ₙ case.  Terminology: 𝒢₃ denotes the *algebra*; an instance of this
    class is an *element of* 𝒢₃.

    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified
    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."""

    DIMENSION: typing.ClassVar[int] = 3

    scalar: numbers.Real = typing.cast(numbers.Real, 0)
    e_1: numbers.Real = typing.cast(numbers.Real, 0)
    e_2: numbers.Real = typing.cast(numbers.Real, 0)
    e_3: numbers.Real = typing.cast(numbers.Real, 0)
    e_12: numbers.Real = typing.cast(numbers.Real, 0)
    e_13: numbers.Real = typing.cast(numbers.Real, 0)
    e_23: numbers.Real = typing.cast(numbers.Real, 0)
    e_123: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            scalar=typing.cast(numbers.Real, d.get((), 0)),
            e_1=typing.cast(numbers.Real, d.get((1,), 0)),
            e_2=typing.cast(numbers.Real, d.get((2,), 0)),
            e_3=typing.cast(numbers.Real, d.get((3,), 0)),
            e_12=typing.cast(numbers.Real, d.get((1, 2), 0)),
            e_13=typing.cast(numbers.Real, d.get((1, 3), 0)),
            e_23=typing.cast(numbers.Real, d.get((2, 3), 0)),
            e_123=typing.cast(numbers.Real, d.get((1, 2, 3), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((), self.scalar),
                ((1,), self.e_1),
                ((2,), self.e_2),
                ((3,), self.e_3),
                ((1, 2), self.e_12),
                ((1, 3), self.e_13),
                ((2, 3), self.e_23),
                ((1, 2, 3), self.e_123),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def _geometric_product(self, rhs) -> typing.Self:
        if not isinstance(rhs, G3):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left * right)
        result = G3(
            scalar=(
                self.e_1 * rhs.e_1
                - self.e_12 * rhs.e_12
                - self.e_123 * rhs.e_123
                - self.e_13 * rhs.e_13
                + self.e_2 * rhs.e_2
                - self.e_23 * rhs.e_23
                + self.e_3 * rhs.e_3
                + self.scalar * rhs.scalar
            ),
            e_1=(
                self.e_1 * rhs.scalar
                + self.e_12 * rhs.e_2
                - self.e_123 * rhs.e_23
                + self.e_13 * rhs.e_3
                - self.e_2 * rhs.e_12
                - self.e_23 * rhs.e_123
                - self.e_3 * rhs.e_13
                + self.scalar * rhs.e_1
            ),
            e_2=(
                self.e_1 * rhs.e_12
                - self.e_12 * rhs.e_1
                + self.e_123 * rhs.e_13
                + self.e_13 * rhs.e_123
                + self.e_2 * rhs.scalar
                + self.e_23 * rhs.e_3
                - self.e_3 * rhs.e_23
                + self.scalar * rhs.e_2
            ),
            e_3=(
                self.e_1 * rhs.e_13
                - self.e_12 * rhs.e_123
                - self.e_123 * rhs.e_12
                - self.e_13 * rhs.e_1
                + self.e_2 * rhs.e_23
                - self.e_23 * rhs.e_2
                + self.e_3 * rhs.scalar
                + self.scalar * rhs.e_3
            ),
            e_12=(
                self.e_1 * rhs.e_2
                + self.e_12 * rhs.scalar
                + self.e_123 * rhs.e_3
                - self.e_13 * rhs.e_23
                - self.e_2 * rhs.e_1
                + self.e_23 * rhs.e_13
                + self.e_3 * rhs.e_123
                + self.scalar * rhs.e_12
            ),
            e_13=(
                self.e_1 * rhs.e_3
                + self.e_12 * rhs.e_23
                - self.e_123 * rhs.e_2
                + self.e_13 * rhs.scalar
                - self.e_2 * rhs.e_123
                - self.e_23 * rhs.e_12
                - self.e_3 * rhs.e_1
                + self.scalar * rhs.e_13
            ),
            e_23=(
                self.e_1 * rhs.e_123
                - self.e_12 * rhs.e_13
                + self.e_123 * rhs.e_1
                + self.e_13 * rhs.e_12
                + self.e_2 * rhs.e_3
                + self.e_23 * rhs.scalar
                - self.e_3 * rhs.e_2
                + self.scalar * rhs.e_23
            ),
            e_123=(
                self.e_1 * rhs.e_23
                + self.e_12 * rhs.e_3
                + self.e_123 * rhs.scalar
                - self.e_13 * rhs.e_2
                - self.e_2 * rhs.e_13
                + self.e_23 * rhs.e_1
                + self.e_3 * rhs.e_12
                + self.scalar * rhs.e_123
            ),
        )
        return typing.cast(typing.Self, result)

    def inner_product(self, rhs) -> typing.Self:
        if not isinstance(rhs, G3):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left.inner_product(right))
        result = G3(
            scalar=(
                self.e_1 * rhs.e_1
                - self.e_12 * rhs.e_12
                - self.e_123 * rhs.e_123
                - self.e_13 * rhs.e_13
                + self.e_2 * rhs.e_2
                - self.e_23 * rhs.e_23
                + self.e_3 * rhs.e_3
            ),
            e_1=(
                self.e_12 * rhs.e_2
                - self.e_123 * rhs.e_23
                + self.e_13 * rhs.e_3
                - self.e_2 * rhs.e_12
                - self.e_23 * rhs.e_123
                - self.e_3 * rhs.e_13
            ),
            e_2=(
                self.e_1 * rhs.e_12
                - self.e_12 * rhs.e_1
                + self.e_123 * rhs.e_13
                + self.e_13 * rhs.e_123
                + self.e_23 * rhs.e_3
                - self.e_3 * rhs.e_23
            ),
            e_3=(
                self.e_1 * rhs.e_13
                - self.e_12 * rhs.e_123
                - self.e_123 * rhs.e_12
                - self.e_13 * rhs.e_1
                + self.e_2 * rhs.e_23
                - self.e_23 * rhs.e_2
            ),
            e_12=self.e_123 * rhs.e_3 + self.e_3 * rhs.e_123,
            e_13=-self.e_123 * rhs.e_2 - self.e_2 * rhs.e_123,
            e_23=self.e_1 * rhs.e_123 + self.e_123 * rhs.e_1,
            e_123=typing.cast(numbers.Real, 0),
        )
        return typing.cast(typing.Self, result)

    def outer_product(self, rhs) -> typing.Self:
        if not isinstance(rhs, G3):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left.outer_product(right))
        result = G3(
            scalar=self.scalar * rhs.scalar,
            e_1=self.e_1 * rhs.scalar + self.scalar * rhs.e_1,
            e_2=self.e_2 * rhs.scalar + self.scalar * rhs.e_2,
            e_3=self.e_3 * rhs.scalar + self.scalar * rhs.e_3,
            e_12=(
                self.e_1 * rhs.e_2
                + self.e_12 * rhs.scalar
                - self.e_2 * rhs.e_1
                + self.scalar * rhs.e_12
            ),
            e_13=(
                self.e_1 * rhs.e_3
                + self.e_13 * rhs.scalar
                - self.e_3 * rhs.e_1
                + self.scalar * rhs.e_13
            ),
            e_23=(
                self.e_2 * rhs.e_3
                + self.e_23 * rhs.scalar
                - self.e_3 * rhs.e_2
                + self.scalar * rhs.e_23
            ),
            e_123=(
                self.e_1 * rhs.e_23
                + self.e_12 * rhs.e_3
                + self.e_123 * rhs.scalar
                - self.e_13 * rhs.e_2
                - self.e_2 * rhs.e_13
                + self.e_23 * rhs.e_1
                + self.e_3 * rhs.e_12
                + self.scalar * rhs.e_123
            ),
        )
        return typing.cast(typing.Self, result)

    def __add__(self, rhs) -> typing.Self:
        if not isinstance(rhs, G3):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left + right)
        result = G3(
            scalar=self.scalar + rhs.scalar,
            e_1=self.e_1 + rhs.e_1,
            e_2=self.e_2 + rhs.e_2,
            e_3=self.e_3 + rhs.e_3,
            e_12=self.e_12 + rhs.e_12,
            e_13=self.e_13 + rhs.e_13,
            e_23=self.e_23 + rhs.e_23,
            e_123=self.e_123 + rhs.e_123,
        )
        return typing.cast(typing.Self, result)

    def __sub__(self, rhs) -> typing.Self:
        if not isinstance(rhs, G3):
            left = Gn.from_blade_dict(self.to_blade_dict())
            right = Gn.from_blade_dict(rhs.to_blade_dict())
            return typing.cast(typing.Self, left - right)
        result = G3(
            scalar=self.scalar - rhs.scalar,
            e_1=self.e_1 - rhs.e_1,
            e_2=self.e_2 - rhs.e_2,
            e_3=self.e_3 - rhs.e_3,
            e_12=self.e_12 - rhs.e_12,
            e_13=self.e_13 - rhs.e_13,
            e_23=self.e_23 - rhs.e_23,
            e_123=self.e_123 - rhs.e_123,
        )
        return typing.cast(typing.Self, result)

    def __neg__(self) -> typing.Self:
        result = G3(
            scalar=typing.cast(numbers.Real, -self.scalar),
            e_1=typing.cast(numbers.Real, -self.e_1),
            e_2=typing.cast(numbers.Real, -self.e_2),
            e_3=typing.cast(numbers.Real, -self.e_3),
            e_12=typing.cast(numbers.Real, -self.e_12),
            e_13=typing.cast(numbers.Real, -self.e_13),
            e_23=typing.cast(numbers.Real, -self.e_23),
            e_123=typing.cast(numbers.Real, -self.e_123),
        )
        return typing.cast(typing.Self, result)

    def scalar_part(self) -> numbers.Real:
        return self.scalar

    def grades(self) -> list[int]:
        present: list[int] = []
        if self.scalar != 0:
            present.append(0)
        if self.e_1 != 0 or self.e_2 != 0 or self.e_3 != 0:
            present.append(1)
        if self.e_12 != 0 or self.e_13 != 0 or self.e_23 != 0:
            present.append(2)
        if self.e_123 != 0:
            present.append(3)
        return present

    def r_vector_part(self, r: int) -> typing.Self:
        if r == 0:
            result = G3(
                scalar=self.scalar,
            )
            return typing.cast(typing.Self, result)
        if r == 1:
            result = G3(
                e_1=self.e_1,
                e_2=self.e_2,
                e_3=self.e_3,
            )
            return typing.cast(typing.Self, result)
        if r == 2:
            result = G3(
                e_12=self.e_12,
                e_13=self.e_13,
                e_23=self.e_23,
            )
            return typing.cast(typing.Self, result)
        if r == 3:
            result = G3(
                e_123=self.e_123,
            )
            return typing.cast(typing.Self, result)
        result = G3()
        return typing.cast(typing.Self, result)

    def reverse(self) -> typing.Self:
        result = G3(
            scalar=self.scalar,
            e_1=self.e_1,
            e_2=self.e_2,
            e_3=self.e_3,
            e_12=typing.cast(numbers.Real, -self.e_12),
            e_13=typing.cast(numbers.Real, -self.e_13),
            e_23=typing.cast(numbers.Real, -self.e_23),
            e_123=typing.cast(numbers.Real, -self.e_123),
        )
        return typing.cast(typing.Self, result)

    def even_part(self) -> typing.Self:
        result = G3(
            scalar=self.scalar,
            e_12=self.e_12,
            e_13=self.e_13,
            e_23=self.e_23,
        )
        return typing.cast(typing.Self, result)

    def odd_part(self) -> typing.Self:
        result = G3(
            e_1=self.e_1,
            e_2=self.e_2,
            e_3=self.e_3,
            e_123=self.e_123,
        )
        return typing.cast(typing.Self, result)

    def is_close(self, other) -> bool:
        if not isinstance(other, G3):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.scalar), float(other.scalar), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_1), float(other.e_1), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_2), float(other.e_2), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_3), float(other.e_3), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_12), float(other.e_12), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_13), float(other.e_13), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_23), float(other.e_23), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_123), float(other.e_123), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.scalar != 0:
            yield G3(scalar=self.scalar)
        if self.e_1 != 0:
            yield G3(e_1=self.e_1)
        if self.e_2 != 0:
            yield G3(e_2=self.e_2)
        if self.e_3 != 0:
            yield G3(e_3=self.e_3)
        if self.e_12 != 0:
            yield G3(e_12=self.e_12)
        if self.e_13 != 0:
            yield G3(e_13=self.e_13)
        if self.e_23 != 0:
            yield G3(e_23=self.e_23)
        if self.e_123 != 0:
            yield G3(e_123=self.e_123)

    def dual(self, n: int | None = None) -> typing.Self:
        return super().dual(self.DIMENSION if n is None else n)

    @classmethod
    def unit_pseudoscalar(cls, n: int | None = None) -> typing.Self:
        return super().unit_pseudoscalar(cls.DIMENSION if n is None else n)

    @classmethod
    def unit_pseudoscalar_squared(cls, n: int | None = None) -> typing.Self:
        return super().unit_pseudoscalar_squared(cls.DIMENSION if n is None else n)

    @classmethod
    def bases(cls, n: int | None = None) -> Generator[typing.Self]:
        return super().bases(cls.DIMENSION if n is None else n)

    @classmethod
    def symbolic_multivector(
        cls, n: int | None = None, prefix: str = "a"
    ) -> typing.Self:
        return super().symbolic_multivector(cls.DIMENSION if n is None else n, prefix)


@dataclasses.dataclass(eq=False)
class Vector3(AbstractMultiVector):
    """An element of the grade-1 (vector) part
    of 𝒢₃.  Stored as the named fields: e_1, e_2, e_3.

    A graded subtype: products dispatch by operand type and return the
    grade-correct type (e.g. vector*vector -> the even/Rotor type).  Results
    that span grades no graded type covers widen to G3.
    AUTO-GENERATED by tools/gen_specialized.py."""

    DIMENSION: typing.ClassVar[int] = 3

    e_1: numbers.Real = typing.cast(numbers.Real, 0)
    e_2: numbers.Real = typing.cast(numbers.Real, 0)
    e_3: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            e_1=typing.cast(numbers.Real, d.get((1,), 0)),
            e_2=typing.cast(numbers.Real, d.get((2,), 0)),
            e_3=typing.cast(numbers.Real, d.get((3,), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((1,), self.e_1),
                ((2,), self.e_2),
                ((3,), self.e_3),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def __mul__(self, rhs) -> typing.Self:
        if isinstance(rhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Vector3(
                    e_1=typing.cast(numbers.Real, self.e_1 * rhs),
                    e_2=typing.cast(numbers.Real, self.e_2 * rhs),
                    e_3=typing.cast(numbers.Real, self.e_3 * rhs),
                ),
            )
        return self._geometric_product(rhs)

    def __rmul__(self, lhs) -> typing.Self:
        if isinstance(lhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Vector3(
                    e_1=typing.cast(numbers.Real, lhs * self.e_1),
                    e_2=typing.cast(numbers.Real, lhs * self.e_2),
                    e_3=typing.cast(numbers.Real, lhs * self.e_3),
                ),
            )
        return self._geometric_product(lhs)

    def _geometric_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=self.e_1 * rhs.scalar,
                        e_2=self.e_2 * rhs.scalar,
                        e_3=self.e_3 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=self.e_1 * rhs.e_1
                        + self.e_2 * rhs.e_2
                        + self.e_3 * rhs.e_3,
                        e_12=self.e_1 * rhs.e_2 - self.e_2 * rhs.e_1,
                        e_13=self.e_1 * rhs.e_3 - self.e_3 * rhs.e_1,
                        e_23=self.e_2 * rhs.e_3 - self.e_3 * rhs.e_2,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=-self.e_2 * rhs.e_12 - self.e_3 * rhs.e_13,
                        e_2=self.e_1 * rhs.e_12 - self.e_3 * rhs.e_23,
                        e_3=self.e_1 * rhs.e_13 + self.e_2 * rhs.e_23,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_1 * rhs.e_23
                        - self.e_2 * rhs.e_13
                        + self.e_3 * rhs.e_12,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_3 * rhs.e_123,
                        e_13=-self.e_2 * rhs.e_123,
                        e_23=self.e_1 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=self.e_1 * rhs.scalar
                        - self.e_2 * rhs.e_12
                        - self.e_3 * rhs.e_13,
                        e_2=self.e_1 * rhs.e_12
                        + self.e_2 * rhs.scalar
                        - self.e_3 * rhs.e_23,
                        e_3=self.e_1 * rhs.e_13
                        + self.e_2 * rhs.e_23
                        + self.e_3 * rhs.scalar,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_1 * rhs.e_23
                        - self.e_2 * rhs.e_13
                        + self.e_3 * rhs.e_12,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left * right)

    def outer_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=self.e_1 * rhs.scalar,
                        e_2=self.e_2 * rhs.scalar,
                        e_3=self.e_3 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_1 * rhs.e_2 - self.e_2 * rhs.e_1,
                        e_13=self.e_1 * rhs.e_3 - self.e_3 * rhs.e_1,
                        e_23=self.e_2 * rhs.e_3 - self.e_3 * rhs.e_2,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Trivector3(
                        e_123=self.e_1 * rhs.e_23
                        - self.e_2 * rhs.e_13
                        + self.e_3 * rhs.e_12,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=self.e_1 * rhs.scalar,
                        e_2=self.e_2 * rhs.scalar,
                        e_3=self.e_3 * rhs.scalar,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_1 * rhs.e_23
                        - self.e_2 * rhs.e_13
                        + self.e_3 * rhs.e_12,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.outer_product(right))

    def inner_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=self.e_1 * rhs.e_1
                        + self.e_2 * rhs.e_2
                        + self.e_3 * rhs.e_3,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_2 * rhs.e_12 - self.e_3 * rhs.e_13,
                        e_2=self.e_1 * rhs.e_12 - self.e_3 * rhs.e_23,
                        e_3=self.e_1 * rhs.e_13 + self.e_2 * rhs.e_23,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_3 * rhs.e_123,
                        e_13=-self.e_2 * rhs.e_123,
                        e_23=self.e_1 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_2 * rhs.e_12 - self.e_3 * rhs.e_13,
                        e_2=self.e_1 * rhs.e_12 - self.e_3 * rhs.e_23,
                        e_3=self.e_1 * rhs.e_13 + self.e_2 * rhs.e_23,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.inner_product(right))

    def __add__(self, rhs) -> typing.Self:
        if isinstance(rhs, Vector3):
            return typing.cast(
                typing.Self,
                Vector3(
                    e_1=self.e_1 + rhs.e_1,
                    e_2=self.e_2 + rhs.e_2,
                    e_3=self.e_3 + rhs.e_3,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left + right)

    def __sub__(self, rhs) -> typing.Self:
        if isinstance(rhs, Vector3):
            return typing.cast(
                typing.Self,
                Vector3(
                    e_1=self.e_1 - rhs.e_1,
                    e_2=self.e_2 - rhs.e_2,
                    e_3=self.e_3 - rhs.e_3,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left - right)

    def __neg__(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Vector3(
                e_1=typing.cast(numbers.Real, -self.e_1),
                e_2=typing.cast(numbers.Real, -self.e_2),
                e_3=typing.cast(numbers.Real, -self.e_3),
            ),
        )

    def reverse(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Vector3(
                e_1=self.e_1,
                e_2=self.e_2,
                e_3=self.e_3,
            ),
        )

    def scalar_part(self) -> numbers.Real:
        return typing.cast(numbers.Real, 0)

    def grades(self) -> list[int]:
        present: list[int] = []
        if self.e_1 != 0 or self.e_2 != 0 or self.e_3 != 0:
            present.append(1)
        return present

    def is_close(self, other) -> bool:
        if not isinstance(other, Vector3):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.e_1), float(other.e_1), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_2), float(other.e_2), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_3), float(other.e_3), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.e_1 != 0:
            yield Vector3(e_1=self.e_1)
        if self.e_2 != 0:
            yield Vector3(e_2=self.e_2)
        if self.e_3 != 0:
            yield Vector3(e_3=self.e_3)

    def even_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).even_part())

    def odd_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).odd_part())

    def r_vector_part(self, r: int) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).r_vector_part(r))

    def dual(self, n: int | None = None) -> typing.Self:
        return typing.cast(
            typing.Self, _coerce(self, G3).dual(self.DIMENSION if n is None else n)
        )


@dataclasses.dataclass(eq=False)
class Bivector3(AbstractMultiVector):
    """An element of the grade-2 (bivector) part
    of 𝒢₃.  Stored as the named fields: e_12, e_13, e_23.

    A graded subtype: products dispatch by operand type and return the
    grade-correct type (e.g. vector*vector -> the even/Rotor type).  Results
    that span grades no graded type covers widen to G3.
    AUTO-GENERATED by tools/gen_specialized.py."""

    DIMENSION: typing.ClassVar[int] = 3

    e_12: numbers.Real = typing.cast(numbers.Real, 0)
    e_13: numbers.Real = typing.cast(numbers.Real, 0)
    e_23: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            e_12=typing.cast(numbers.Real, d.get((1, 2), 0)),
            e_13=typing.cast(numbers.Real, d.get((1, 3), 0)),
            e_23=typing.cast(numbers.Real, d.get((2, 3), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((1, 2), self.e_12),
                ((1, 3), self.e_13),
                ((2, 3), self.e_23),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def __mul__(self, rhs) -> typing.Self:
        if isinstance(rhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Bivector3(
                    e_12=typing.cast(numbers.Real, self.e_12 * rhs),
                    e_13=typing.cast(numbers.Real, self.e_13 * rhs),
                    e_23=typing.cast(numbers.Real, self.e_23 * rhs),
                ),
            )
        return self._geometric_product(rhs)

    def __rmul__(self, lhs) -> typing.Self:
        if isinstance(lhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Bivector3(
                    e_12=typing.cast(numbers.Real, lhs * self.e_12),
                    e_13=typing.cast(numbers.Real, lhs * self.e_13),
                    e_23=typing.cast(numbers.Real, lhs * self.e_23),
                ),
            )
        return self._geometric_product(lhs)

    def _geometric_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_12 * rhs.scalar,
                        e_13=self.e_13 * rhs.scalar,
                        e_23=self.e_23 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=self.e_12 * rhs.e_2 + self.e_13 * rhs.e_3,
                        e_2=-self.e_12 * rhs.e_1 + self.e_23 * rhs.e_3,
                        e_3=-self.e_13 * rhs.e_1 - self.e_23 * rhs.e_2,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_12 * rhs.e_3
                        - self.e_13 * rhs.e_2
                        + self.e_23 * rhs.e_1,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                        e_12=-self.e_13 * rhs.e_23 + self.e_23 * rhs.e_13,
                        e_13=self.e_12 * rhs.e_23 - self.e_23 * rhs.e_12,
                        e_23=-self.e_12 * rhs.e_13 + self.e_13 * rhs.e_12,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_23 * rhs.e_123,
                        e_2=self.e_13 * rhs.e_123,
                        e_3=-self.e_12 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                        e_12=(
                            self.e_12 * rhs.scalar
                            - self.e_13 * rhs.e_23
                            + self.e_23 * rhs.e_13
                        ),
                        e_13=(
                            self.e_12 * rhs.e_23
                            + self.e_13 * rhs.scalar
                            - self.e_23 * rhs.e_12
                        ),
                        e_23=(
                            -self.e_12 * rhs.e_13
                            + self.e_13 * rhs.e_12
                            + self.e_23 * rhs.scalar
                        ),
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left * right)

    def outer_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_12 * rhs.scalar,
                        e_13=self.e_13 * rhs.scalar,
                        e_23=self.e_23 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Trivector3(
                        e_123=self.e_12 * rhs.e_3
                        - self.e_13 * rhs.e_2
                        + self.e_23 * rhs.e_1,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_12 * rhs.scalar,
                        e_13=self.e_13 * rhs.scalar,
                        e_23=self.e_23 * rhs.scalar,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.outer_product(right))

    def inner_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=self.e_12 * rhs.e_2 + self.e_13 * rhs.e_3,
                        e_2=-self.e_12 * rhs.e_1 + self.e_23 * rhs.e_3,
                        e_3=-self.e_13 * rhs.e_1 - self.e_23 * rhs.e_2,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_23 * rhs.e_123,
                        e_2=self.e_13 * rhs.e_123,
                        e_3=-self.e_12 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.inner_product(right))

    def __add__(self, rhs) -> typing.Self:
        if isinstance(rhs, Bivector3):
            return typing.cast(
                typing.Self,
                Bivector3(
                    e_12=self.e_12 + rhs.e_12,
                    e_13=self.e_13 + rhs.e_13,
                    e_23=self.e_23 + rhs.e_23,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left + right)

    def __sub__(self, rhs) -> typing.Self:
        if isinstance(rhs, Bivector3):
            return typing.cast(
                typing.Self,
                Bivector3(
                    e_12=self.e_12 - rhs.e_12,
                    e_13=self.e_13 - rhs.e_13,
                    e_23=self.e_23 - rhs.e_23,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left - right)

    def __neg__(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Bivector3(
                e_12=typing.cast(numbers.Real, -self.e_12),
                e_13=typing.cast(numbers.Real, -self.e_13),
                e_23=typing.cast(numbers.Real, -self.e_23),
            ),
        )

    def reverse(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Bivector3(
                e_12=typing.cast(numbers.Real, -self.e_12),
                e_13=typing.cast(numbers.Real, -self.e_13),
                e_23=typing.cast(numbers.Real, -self.e_23),
            ),
        )

    def scalar_part(self) -> numbers.Real:
        return typing.cast(numbers.Real, 0)

    def grades(self) -> list[int]:
        present: list[int] = []
        if self.e_12 != 0 or self.e_13 != 0 or self.e_23 != 0:
            present.append(2)
        return present

    def is_close(self, other) -> bool:
        if not isinstance(other, Bivector3):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.e_12), float(other.e_12), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_13), float(other.e_13), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_23), float(other.e_23), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.e_12 != 0:
            yield Bivector3(e_12=self.e_12)
        if self.e_13 != 0:
            yield Bivector3(e_13=self.e_13)
        if self.e_23 != 0:
            yield Bivector3(e_23=self.e_23)

    def even_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).even_part())

    def odd_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).odd_part())

    def r_vector_part(self, r: int) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).r_vector_part(r))

    def dual(self, n: int | None = None) -> typing.Self:
        return typing.cast(
            typing.Self, _coerce(self, G3).dual(self.DIMENSION if n is None else n)
        )


@dataclasses.dataclass(eq=False)
class Trivector3(AbstractMultiVector):
    """An element of the grade-3 (trivector) part
    of 𝒢₃.  Stored as the named fields: e_123.

    A graded subtype: products dispatch by operand type and return the
    grade-correct type (e.g. vector*vector -> the even/Rotor type).  Results
    that span grades no graded type covers widen to G3.
    AUTO-GENERATED by tools/gen_specialized.py."""

    DIMENSION: typing.ClassVar[int] = 3

    e_123: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            e_123=typing.cast(numbers.Real, d.get((1, 2, 3), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {blade: coef for blade, coef in (((1, 2, 3), self.e_123),) if coef != 0}

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def __mul__(self, rhs) -> typing.Self:
        if isinstance(rhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Trivector3(
                    e_123=typing.cast(numbers.Real, self.e_123 * rhs),
                ),
            )
        return self._geometric_product(rhs)

    def __rmul__(self, lhs) -> typing.Self:
        if isinstance(lhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Trivector3(
                    e_123=typing.cast(numbers.Real, lhs * self.e_123),
                ),
            )
        return self._geometric_product(lhs)

    def _geometric_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Trivector3(
                        e_123=self.e_123 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_123 * rhs.e_3,
                        e_13=-self.e_123 * rhs.e_2,
                        e_23=self.e_123 * rhs.e_1,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_123 * rhs.e_23,
                        e_2=self.e_123 * rhs.e_13,
                        e_3=-self.e_123 * rhs.e_12,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=-self.e_123 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=-self.e_123 * rhs.e_23,
                        e_2=self.e_123 * rhs.e_13,
                        e_3=-self.e_123 * rhs.e_12,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_123 * rhs.scalar,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left * right)

    def outer_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Trivector3(
                        e_123=self.e_123 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Trivector3(
                        e_123=self.e_123 * rhs.scalar,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.outer_product(right))

    def inner_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.e_123 * rhs.e_3,
                        e_13=-self.e_123 * rhs.e_2,
                        e_23=self.e_123 * rhs.e_1,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_123 * rhs.e_23,
                        e_2=self.e_123 * rhs.e_13,
                        e_3=-self.e_123 * rhs.e_12,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=-self.e_123 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_123 * rhs.e_23,
                        e_2=self.e_123 * rhs.e_13,
                        e_3=-self.e_123 * rhs.e_12,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.inner_product(right))

    def __add__(self, rhs) -> typing.Self:
        if isinstance(rhs, Trivector3):
            return typing.cast(
                typing.Self,
                Trivector3(
                    e_123=self.e_123 + rhs.e_123,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left + right)

    def __sub__(self, rhs) -> typing.Self:
        if isinstance(rhs, Trivector3):
            return typing.cast(
                typing.Self,
                Trivector3(
                    e_123=self.e_123 - rhs.e_123,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left - right)

    def __neg__(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Trivector3(
                e_123=typing.cast(numbers.Real, -self.e_123),
            ),
        )

    def reverse(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Trivector3(
                e_123=typing.cast(numbers.Real, -self.e_123),
            ),
        )

    def scalar_part(self) -> numbers.Real:
        return typing.cast(numbers.Real, 0)

    def grades(self) -> list[int]:
        present: list[int] = []
        if self.e_123 != 0:
            present.append(3)
        return present

    def is_close(self, other) -> bool:
        if not isinstance(other, Trivector3):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.e_123), float(other.e_123), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.e_123 != 0:
            yield Trivector3(e_123=self.e_123)

    def even_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).even_part())

    def odd_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).odd_part())

    def r_vector_part(self, r: int) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).r_vector_part(r))

    def dual(self, n: int | None = None) -> typing.Self:
        return typing.cast(
            typing.Self, _coerce(self, G3).dual(self.DIMENSION if n is None else n)
        )


@dataclasses.dataclass(eq=False)
class Rotor3(AbstractMultiVector):
    """An element of the even subalgebra (rotor / spinor)
    of 𝒢₃.  Stored as the named fields: scalar, e_12, e_13, e_23.

    A graded subtype: products dispatch by operand type and return the
    grade-correct type (e.g. vector*vector -> the even/Rotor type).  Results
    that span grades no graded type covers widen to G3.
    AUTO-GENERATED by tools/gen_specialized.py."""

    DIMENSION: typing.ClassVar[int] = 3

    scalar: numbers.Real = typing.cast(numbers.Real, 0)
    e_12: numbers.Real = typing.cast(numbers.Real, 0)
    e_13: numbers.Real = typing.cast(numbers.Real, 0)
    e_23: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(
            scalar=typing.cast(numbers.Real, d.get((), 0)),
            e_12=typing.cast(numbers.Real, d.get((1, 2), 0)),
            e_13=typing.cast(numbers.Real, d.get((1, 3), 0)),
            e_23=typing.cast(numbers.Real, d.get((2, 3), 0)),
        )

    def to_blade_dict(self) -> BladeCoef:
        return {
            blade: coef
            for blade, coef in (
                ((), self.scalar),
                ((1, 2), self.e_12),
                ((1, 3), self.e_13),
                ((2, 3), self.e_23),
            )
            if coef != 0
        }

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def __mul__(self, rhs) -> typing.Self:
        if isinstance(rhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Rotor3(
                    scalar=typing.cast(numbers.Real, self.scalar * rhs),
                    e_12=typing.cast(numbers.Real, self.e_12 * rhs),
                    e_13=typing.cast(numbers.Real, self.e_13 * rhs),
                    e_23=typing.cast(numbers.Real, self.e_23 * rhs),
                ),
            )
        return self._geometric_product(rhs)

    def __rmul__(self, lhs) -> typing.Self:
        if isinstance(lhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self,
                Rotor3(
                    scalar=typing.cast(numbers.Real, lhs * self.scalar),
                    e_12=typing.cast(numbers.Real, lhs * self.e_12),
                    e_13=typing.cast(numbers.Real, lhs * self.e_13),
                    e_23=typing.cast(numbers.Real, lhs * self.e_23),
                ),
            )
        return self._geometric_product(lhs)

    def _geometric_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=self.scalar * rhs.scalar,
                        e_12=self.e_12 * rhs.scalar,
                        e_13=self.e_13 * rhs.scalar,
                        e_23=self.e_23 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=self.e_12 * rhs.e_2
                        + self.e_13 * rhs.e_3
                        + self.scalar * rhs.e_1,
                        e_2=(
                            -self.e_12 * rhs.e_1
                            + self.e_23 * rhs.e_3
                            + self.scalar * rhs.e_2
                        ),
                        e_3=(
                            -self.e_13 * rhs.e_1
                            - self.e_23 * rhs.e_2
                            + self.scalar * rhs.e_3
                        ),
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_12 * rhs.e_3
                        - self.e_13 * rhs.e_2
                        + self.e_23 * rhs.e_1,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                        e_12=(
                            -self.e_13 * rhs.e_23
                            + self.e_23 * rhs.e_13
                            + self.scalar * rhs.e_12
                        ),
                        e_13=(
                            self.e_12 * rhs.e_23
                            - self.e_23 * rhs.e_12
                            + self.scalar * rhs.e_13
                        ),
                        e_23=(
                            -self.e_12 * rhs.e_13
                            + self.e_13 * rhs.e_12
                            + self.scalar * rhs.e_23
                        ),
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=-self.e_23 * rhs.e_123,
                        e_2=self.e_13 * rhs.e_123,
                        e_3=-self.e_12 * rhs.e_123,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.scalar * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                            + self.scalar * rhs.scalar
                        ),
                        e_12=(
                            self.e_12 * rhs.scalar
                            - self.e_13 * rhs.e_23
                            + self.e_23 * rhs.e_13
                            + self.scalar * rhs.e_12
                        ),
                        e_13=(
                            self.e_12 * rhs.e_23
                            + self.e_13 * rhs.scalar
                            - self.e_23 * rhs.e_12
                            + self.scalar * rhs.e_13
                        ),
                        e_23=(
                            -self.e_12 * rhs.e_13
                            + self.e_13 * rhs.e_12
                            + self.e_23 * rhs.scalar
                            + self.scalar * rhs.e_23
                        ),
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left * right)

    def outer_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=self.scalar * rhs.scalar,
                        e_12=self.e_12 * rhs.scalar,
                        e_13=self.e_13 * rhs.scalar,
                        e_23=self.e_23 * rhs.scalar,
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    G3(
                        scalar=typing.cast(numbers.Real, 0),
                        e_1=self.scalar * rhs.e_1,
                        e_2=self.scalar * rhs.e_2,
                        e_3=self.scalar * rhs.e_3,
                        e_12=typing.cast(numbers.Real, 0),
                        e_13=typing.cast(numbers.Real, 0),
                        e_23=typing.cast(numbers.Real, 0),
                        e_123=self.e_12 * rhs.e_3
                        - self.e_13 * rhs.e_2
                        + self.e_23 * rhs.e_1,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Bivector3(
                        e_12=self.scalar * rhs.e_12,
                        e_13=self.scalar * rhs.e_13,
                        e_23=self.scalar * rhs.e_23,
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Trivector3(
                        e_123=self.scalar * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Rotor3(
                        scalar=self.scalar * rhs.scalar,
                        e_12=self.e_12 * rhs.scalar + self.scalar * rhs.e_12,
                        e_13=self.e_13 * rhs.scalar + self.scalar * rhs.e_13,
                        e_23=self.e_23 * rhs.scalar + self.scalar * rhs.e_23,
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.outer_product(right))

    def inner_product(self, rhs) -> typing.Self:
        match rhs:
            case Scalar():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=typing.cast(numbers.Real, 0),
                    ),
                )
            case Vector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=self.e_12 * rhs.e_2 + self.e_13 * rhs.e_3,
                        e_2=-self.e_12 * rhs.e_1 + self.e_23 * rhs.e_3,
                        e_3=-self.e_13 * rhs.e_1 - self.e_23 * rhs.e_2,
                    ),
                )
            case Bivector3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                    ),
                )
            case Trivector3():
                return typing.cast(
                    typing.Self,
                    Vector3(
                        e_1=-self.e_23 * rhs.e_123,
                        e_2=self.e_13 * rhs.e_123,
                        e_3=-self.e_12 * rhs.e_123,
                    ),
                )
            case Rotor3():
                return typing.cast(
                    typing.Self,
                    Scalar(
                        scalar=(
                            -self.e_12 * rhs.e_12
                            - self.e_13 * rhs.e_13
                            - self.e_23 * rhs.e_23
                        ),
                    ),
                )
            case _:
                left = _coerce(self, G3)
                right = _coerce(rhs, G3)
                return typing.cast(typing.Self, left.inner_product(right))

    def __add__(self, rhs) -> typing.Self:
        if isinstance(rhs, Rotor3):
            return typing.cast(
                typing.Self,
                Rotor3(
                    scalar=self.scalar + rhs.scalar,
                    e_12=self.e_12 + rhs.e_12,
                    e_13=self.e_13 + rhs.e_13,
                    e_23=self.e_23 + rhs.e_23,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left + right)

    def __sub__(self, rhs) -> typing.Self:
        if isinstance(rhs, Rotor3):
            return typing.cast(
                typing.Self,
                Rotor3(
                    scalar=self.scalar - rhs.scalar,
                    e_12=self.e_12 - rhs.e_12,
                    e_13=self.e_13 - rhs.e_13,
                    e_23=self.e_23 - rhs.e_23,
                ),
            )
        left = _coerce(self, G3)
        right = _coerce(rhs, G3)
        return typing.cast(typing.Self, left - right)

    def __neg__(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Rotor3(
                scalar=typing.cast(numbers.Real, -self.scalar),
                e_12=typing.cast(numbers.Real, -self.e_12),
                e_13=typing.cast(numbers.Real, -self.e_13),
                e_23=typing.cast(numbers.Real, -self.e_23),
            ),
        )

    def reverse(self) -> typing.Self:
        return typing.cast(
            typing.Self,
            Rotor3(
                scalar=self.scalar,
                e_12=typing.cast(numbers.Real, -self.e_12),
                e_13=typing.cast(numbers.Real, -self.e_13),
                e_23=typing.cast(numbers.Real, -self.e_23),
            ),
        )

    def scalar_part(self) -> numbers.Real:
        return self.scalar

    def grades(self) -> list[int]:
        present: list[int] = []
        if self.scalar != 0:
            present.append(0)
        if self.e_12 != 0 or self.e_13 != 0 or self.e_23 != 0:
            present.append(2)
        return present

    def is_close(self, other) -> bool:
        if not isinstance(other, Rotor3):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.scalar), float(other.scalar), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_12), float(other.e_12), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_13), float(other.e_13), rtol=1e-5, atol=1e-5)
            and np.isclose(float(self.e_23), float(other.e_23), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.scalar != 0:
            yield Rotor3(scalar=self.scalar)
        if self.e_12 != 0:
            yield Rotor3(e_12=self.e_12)
        if self.e_13 != 0:
            yield Rotor3(e_13=self.e_13)
        if self.e_23 != 0:
            yield Rotor3(e_23=self.e_23)

    def even_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).even_part())

    def odd_part(self) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).odd_part())

    def r_vector_part(self, r: int) -> typing.Self:
        return typing.cast(typing.Self, _coerce(self, G3).r_vector_part(r))

    def dual(self, n: int | None = None) -> typing.Self:
        return typing.cast(
            typing.Self, _coerce(self, G3).dual(self.DIMENSION if n is None else n)
        )


zero: G3 = G3.from_scalar(0)
one: G3 = G3.from_scalar(1)
e_1: G3 = G3.from_blade_dict({(1,): 1})
e_2: G3 = G3.from_blade_dict({(2,): 1})
e_3: G3 = G3.from_blade_dict({(3,): 1})
e_12: G3 = G3.from_blade_dict({(1, 2): 1})
e_13: G3 = G3.from_blade_dict({(1, 3): 1})
e_23: G3 = G3.from_blade_dict({(2, 3): 1})
e_123: G3 = G3.from_blade_dict({(1, 2, 3): 1})

__all__ = [
    "G3",
    "Scalar",
    "Vector3",
    "Bivector3",
    "Trivector3",
    "Rotor3",
    "zero",
    "one",
    "e_1",
    "e_2",
    "e_3",
    "e_12",
    "e_13",
    "e_23",
    "e_123",
]
