# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# AUTO-GENERATED by tools/gen_specialized.py -- do not edit by hand.
# Regenerate with:  python tools/gen_specialized.py
#
# Scalar: the shared grade-0 type used by the graded subtypes of every 𝒢ₙ.

from __future__ import annotations

import dataclasses
import numbers
import typing

import numpy as np
import sympy

from geometricalgebra.base import AbstractMultiVector, BladeCoef
from geometricalgebra.gn import Gn


@dataclasses.dataclass(eq=False)
class Scalar(AbstractMultiVector):
    """The grade-0 type -- a scalar, shared across every 𝒢ₙ.

    ``Scalar * x`` scales ``x`` and returns x's type; pure-scalar product
    results (e.g. Bivector2 * Bivector2) land here.  AUTO-GENERATED by
    tools/gen_specialized.py."""

    scalar: numbers.Real = typing.cast(numbers.Real, 0)

    @classmethod
    def from_blade_dict(cls, blade_coef) -> typing.Self:
        d = dict(blade_coef)
        return cls(scalar=typing.cast(numbers.Real, d.get((), 0)))

    def to_blade_dict(self) -> BladeCoef:
        return {(): self.scalar} if self.scalar != 0 else {}

    def __eq__(self, other) -> bool:
        if not isinstance(other, AbstractMultiVector):
            return NotImplemented
        left = self.to_blade_dict()
        right = other.to_blade_dict()
        return all(
            sympy.simplify(
                sympy.sympify(left.get(blade, 0)) - sympy.sympify(right.get(blade, 0))
            )
            == 0
            for blade in (set(left.keys()) | set(right.keys()))
        )

    def __mul__(self, rhs) -> typing.Self:
        if isinstance(rhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self, Scalar(scalar=typing.cast(numbers.Real, self.scalar * rhs))
            )
        return self._geometric_product(rhs)

    def __rmul__(self, lhs) -> typing.Self:
        if isinstance(lhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self, Scalar(scalar=typing.cast(numbers.Real, lhs * self.scalar))
            )
        return self._geometric_product(lhs)

    def _geometric_product(self, rhs) -> typing.Self:
        if isinstance(rhs, Scalar):
            return typing.cast(
                typing.Self,
                Scalar(scalar=typing.cast(numbers.Real, self.scalar * rhs.scalar)),
            )
        if isinstance(rhs, AbstractMultiVector):
            return typing.cast(typing.Self, self.scalar * rhs)
        return typing.cast(
            typing.Self, Scalar(scalar=typing.cast(numbers.Real, self.scalar * rhs))
        )

    def outer_product(self, rhs) -> typing.Self:
        return self._geometric_product(rhs)

    def inner_product(self, rhs) -> typing.Self:
        left: Gn = Gn.from_blade_dict(self.to_blade_dict())
        right: Gn = Gn.from_blade_dict(rhs.to_blade_dict())
        return typing.cast(typing.Self, left.inner_product(right))

    def __add__(self, rhs) -> typing.Self:
        if isinstance(rhs, (int, float, sympy.Expr)):
            return typing.cast(
                typing.Self, Scalar(scalar=typing.cast(numbers.Real, self.scalar + rhs))
            )
        if isinstance(rhs, Scalar):
            return typing.cast(typing.Self, Scalar(scalar=self.scalar + rhs.scalar))
        if isinstance(rhs, AbstractMultiVector):
            return typing.cast(typing.Self, rhs + self)
        return typing.cast(typing.Self, NotImplemented)

    def __radd__(self, lhs) -> typing.Self:
        return self.__add__(lhs)

    def __sub__(self, rhs) -> typing.Self:
        return self + (-1 * rhs)

    def __rsub__(self, lhs) -> typing.Self:
        return (-self) + lhs

    def __neg__(self) -> typing.Self:
        return typing.cast(
            typing.Self, Scalar(scalar=typing.cast(numbers.Real, -self.scalar))
        )

    def reverse(self) -> typing.Self:
        return typing.cast(typing.Self, Scalar(scalar=self.scalar))

    def scalar_part(self) -> numbers.Real:
        return self.scalar

    def grades(self) -> list[int]:
        return [0] if self.scalar != 0 else []

    def is_close(self, other) -> bool:
        if not isinstance(other, Scalar):
            return super().is_close(other)
        return bool(
            np.isclose(float(self.scalar), float(other.scalar), rtol=1e-5, atol=1e-5)
        )

    def __iter__(self):
        if self.scalar != 0:
            yield Scalar(scalar=self.scalar)

    def even_part(self) -> typing.Self:
        return typing.cast(typing.Self, Scalar(scalar=self.scalar))

    def odd_part(self) -> typing.Self:
        return typing.cast(typing.Self, Scalar(scalar=typing.cast(numbers.Real, 0)))

    def r_vector_part(self, r: int) -> typing.Self:
        if r == 0:
            return typing.cast(typing.Self, Scalar(scalar=self.scalar))
        return typing.cast(typing.Self, Scalar(scalar=typing.cast(numbers.Real, 0)))

    def dual(self, n: int | None = None) -> typing.Self:
        if n is None:
            raise ValueError("Scalar.dual needs an explicit dimension n")
        return typing.cast(
            typing.Self, Gn.from_blade_dict(self.to_blade_dict()).dual(n)
        )


__all__ = ["Scalar"]
