#!/usr/bin/env python
# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

"""Generate the specialized G1 / G2 / G3 multivector classes.

These are named-field dataclasses for 𝒢₁, 𝒢₂ and 𝒢₃ whose ``_geometric_product``
is the closed-form product, derived *from the general Gn symbolic product* so the
fast path is provably consistent with the reference implementation.  Common
sub-expressions are factored out with ``sympy.cse``.

Each algebra is written to its own committed module -- ``g1.py``, ``g2.py``,
``g3.py`` -- so a newcomer can import just the one they need
(``from geometricalgebra.g2 import G2``).  Re-run this script by hand when the
algebra changes:

    python tools/gen_specialized.py
"""

import os
import re
import sys
from itertools import chain, combinations

import sympy

# allow running from the repo root without installing the package
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from geometricalgebra.multivector import Gn  # noqa: E402


def out_path(filename: str) -> str:
    return os.path.join(
        os.path.dirname(__file__), "..", "src", "geometricalgebra", filename
    )


def blades_for_dim(n: int) -> list[tuple[int, ...]]:
    """All 2**n basis blades of 𝒢ₙ in canonical (grade, then index) order."""
    idx = list(range(1, n + 1))
    powerset = chain.from_iterable(combinations(idx, r) for r in range(n + 1))
    return sorted(powerset, key=lambda b: (len(b), b))


def field_name(blade: tuple[int, ...]) -> str:
    """() -> 'scalar', (1,) -> 'e_1', (1, 2) -> 'e_12', (1, 2, 3) -> 'e_123'."""
    if blade == ():
        return "scalar"
    return "e_" + "".join(str(i) for i in blade)


def format_assignment(lhs: str, expr, indent: str, render) -> list[str]:
    """Render ``<lhs>=<expr>,`` for a constructor kwarg, wrapping long sums.

    Short expressions stay on one line; long ones are split across lines one
    additive term at a time so no line exceeds the formatter's limit.  ``render``
    turns a sympy expression into source text (e.g. ``self.e_1 * rhs.e_2``).
    """
    expr = sympy.sympify(expr)
    inline = f"{indent}{lhs}={render(expr)},"
    if len(inline) <= 88:
        return [inline]

    terms = expr.as_ordered_terms() if expr.is_Add else [expr]
    cont = indent + "    "
    lines = [f"{indent}{lhs}=("]
    for i, term in enumerate(terms):
        s = render(term)
        if i == 0:
            lines.append(f"{cont}{s}")
        elif s.startswith("-"):
            lines.append(f"{cont}- {s[1:].lstrip()}")
        else:
            lines.append(f"{cont}+ {s}")
    lines.append(f"{indent}),")
    return lines


def blade_literal(blade: tuple[int, ...]) -> str:
    """Python source for the blade tuple key, e.g. '()' or '(1,)' or '(1, 2)'."""
    if blade == ():
        return "()"
    if len(blade) == 1:
        return f"({blade[0]},)"
    return "(" + ", ".join(str(i) for i in blade) + ")"


DOCSTRINGS = {
    1: (
        "An element (multivector) of 𝒢₁, the geometric algebra of the Euclidean\n"
        "    line ℝ¹ (Hestenes' notation) -- the simplest geometric algebra.\n"
        "\n"
        "    𝒢₁ has 2¹ = 2 basis blades, stored as named fields:\n"
        "        scalar          grade 0 (scalar)\n"
        "        e_1             grade 1 (the lone vector / pseudoscalar)\n"
        "\n"
        "    A specialized, performant representation of 𝒢₁; see Gn for the general\n"
        "    𝒢ₙ case.  Terminology: 𝒢₁ denotes the *algebra*; an instance of this\n"
        "    class is an *element of* 𝒢₁.\n"
        "\n"
        "    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified\n"
        "    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."
    ),
    2: (
        "An element (multivector) of 𝒢₂, the geometric algebra of the Euclidean\n"
        "    plane ℝ² (Hestenes' notation).\n"
        "\n"
        "    𝒢₂ has 2² = 4 basis blades, stored as named fields:\n"
        "        scalar          grade 0 (scalar)\n"
        "        e_1, e_2        grade 1 (vectors)\n"
        "        e_12            grade 2 (bivector / pseudoscalar)\n"
        "\n"
        "    A specialized, performant representation of 𝒢₂; see Gn for the general\n"
        "    𝒢ₙ case.  Terminology: 𝒢₂ denotes the *algebra*; an instance of this\n"
        "    class is an *element of* 𝒢₂.\n"
        "\n"
        "    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified\n"
        "    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."
    ),
    3: (
        "An element (multivector) of 𝒢₃, the geometric algebra of 3D Euclidean\n"
        '    space ℝ³ (Hestenes\' "algebra of physical space"; the Pauli algebra).\n'
        "\n"
        "    𝒢₃ has 2³ = 8 basis blades, stored as named fields:\n"
        "        scalar                  grade 0 (scalar)\n"
        "        e_1, e_2, e_3           grade 1 (vectors)\n"
        "        e_12, e_13, e_23        grade 2 (bivectors)\n"
        "        e_123                   grade 3 (trivector / pseudoscalar)\n"
        "\n"
        "    A specialized, performant representation of 𝒢₃; see Gn for the general\n"
        "    𝒢ₙ case.  Terminology: 𝒢₃ denotes the *algebra*; an instance of this\n"
        "    class is an *element of* 𝒢₃.\n"
        "\n"
        "    Coefficients are NOT eagerly simplified (unlike Gn); they are simplified\n"
        "    lazily, on equality.  AUTO-GENERATED by tools/gen_specialized.py."
    ),
}


def generate_class(n: int, name: str) -> str:
    blades = blades_for_dim(n)
    fields = [field_name(b) for b in blades]

    # symbolic operands for self/rhs; rendered straight back to attribute access
    # (``a_e_1`` -> ``self.e_1``, ``b_e_12`` -> ``rhs.e_12``) so the generated
    # product has no pointless alias locals.
    a_syms = {b: sympy.Symbol("a_" + field_name(b)) for b in blades}
    b_syms = {b: sympy.Symbol("b_" + field_name(b)) for b in blades}

    rename = {}
    for b in blades:
        rename["a_" + field_name(b)] = "self." + field_name(b)
        rename["b_" + field_name(b)] = "rhs." + field_name(b)
    token = re.compile(r"\b(" + "|".join(re.escape(k) for k in rename) + r")\b")

    def render(expr) -> str:
        return token.sub(lambda m: rename[m.group(1)], sympy.sstr(expr))

    product = Gn.from_blade_dict(a_syms) * Gn.from_blade_dict(b_syms)
    pd = product.to_blade_dict()
    out_exprs = [sympy.sympify(pd.get(b, 0)) for b in blades]

    # common-subexpression elimination across all output components
    replacements, reduced = sympy.cse(out_exprs)

    lines: list[str] = []
    ap = lines.append

    ap("@dataclasses.dataclass(eq=False)")
    ap(f"class {name}(AbstractMultiVector):")
    ap(f'    """{DOCSTRINGS[n]}"""')
    ap("")
    for b in blades:
        ap(f"    {field_name(b)}: numbers.Real = typing.cast(numbers.Real, 0)")
    ap("")

    # from_blade_dict
    ap("    @classmethod")
    ap("    def from_blade_dict(cls, blade_coef) -> typing.Self:")
    ap("        d = dict(blade_coef)")
    ap("        return cls(")
    for b in blades:
        ap(
            f"            {field_name(b)}=typing.cast("
            f"numbers.Real, d.get({blade_literal(b)}, 0)),"
        )
    ap("        )")
    ap("")

    # to_blade_dict
    ap("    def to_blade_dict(self) -> BladeCoef:")
    ap("        return {")
    ap("            blade: coef")
    ap("            for blade, coef in (")
    for b in blades:
        ap(f"                ({blade_literal(b)}, self.{field_name(b)}),")
    ap("            )")
    ap("            if coef != 0")
    ap("        }")
    ap("")

    # __eq__ (simplify lazily, here -- works against any representation)
    ap("    def __eq__(self, other) -> bool:")
    ap("        if not isinstance(other, AbstractMultiVector):")
    ap("            return NotImplemented")
    ap("        left = self.to_blade_dict()")
    ap("        right = other.to_blade_dict()")
    ap("        return all(")
    ap("            sympy.simplify(")
    ap(
        "                sympy.sympify(left.get(blade, 0))"
        " - sympy.sympify(right.get(blade, 0))"
    )
    ap("            )")
    ap("            == 0")
    ap("            for blade in (set(left.keys()) | set(right.keys()))")
    ap("        )")
    ap("")

    # _geometric_product (closed form; coerce to Gn if mixed with another rep)
    ap("    def _geometric_product(self, rhs) -> typing.Self:")
    ap(f"        if not isinstance(rhs, {name}):")
    ap("            left = Gn.from_blade_dict(self.to_blade_dict())")
    ap("            right = Gn.from_blade_dict(rhs.to_blade_dict())")
    ap("            return typing.cast(typing.Self, left * right)")
    for tmp, expr in replacements:
        ap(f"        {render(tmp)} = {render(expr)}")
    ap(f"        result = {name}(")
    for field, expr in zip(fields, reduced):
        lines.extend(format_assignment(field, expr, "            ", render))
    ap("        )")
    ap("        return typing.cast(typing.Self, result)")

    return "\n".join(lines)


def header(name: str, n: int) -> str:
    return f"""# Copyright (c) 2025-2026 William Emerison Six
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# AUTO-GENERATED by tools/gen_specialized.py -- do not edit by hand.
# Regenerate with:  python tools/gen_specialized.py
#
# {name}: a specialized, performant representation of 𝒢{"₁₂₃"[n - 1]} -- a named-field
# dataclass whose geometric product is the closed form derived from the general
# Gn symbolic product.

import dataclasses
import numbers
import typing

import sympy

from geometricalgebra.base import AbstractMultiVector, BladeCoef
from geometricalgebra.gn import Gn
"""


ALGEBRAS = [(1, "G1", "g1.py"), (2, "G2", "g2.py"), (3, "G3", "g3.py")]


def main() -> None:
    for n, name, filename in ALGEBRAS:
        source = "\n".join([header(name, n), "", generate_class(n, name), ""])
        with open(out_path(filename), "w") as f:
            f.write(source)
        sys.stdout.write(f"wrote {os.path.normpath(out_path(filename))}\n")


if __name__ == "__main__":
    main()
