#!/usr/bin/env bash
#
# 02-configure.sh  —  turn the bare Sphinx project into the gacalc book
# =============================================================================
#
# WHAT THIS DOES
#   01-quickstart.sh created a plain, default Sphinx project. This script
#   customizes it to resemble the modelviewprojection book:
#
#     1. adds our settings to the bottom of book/docs/conf.py
#        (theme, add-ons, math rendering, and the PDF/LaTeX options)
#     2. replaces the front page (index.rst) with our own
#     3. writes an API page (api.rst) that pulls in gacalc's docstrings
#     4. writes a small stylesheet (_static/custom.css)
#
#   We ADD our conf.py settings at the end of the file rather than editing the
#   lines sphinx-quickstart wrote. That works because Python reads the file top
#   to bottom, so whenever we set something a second time (like the theme) our
#   value at the bottom is the one that wins.
#
# HOW TO RUN
#   From the top folder of the repository, AFTER 01-quickstart.sh:
#
#       bash tasks/adhoc/sphinx-book-pipeline/02-configure.sh
#
# IMPORTANT: temporary scaffolding — deleted once the book builds. The files it
#   writes under book/docs/ are what we keep.
# =============================================================================

set -eu

BOOK_DIR="book/docs"

# Safety check: make sure 01-quickstart.sh has already run.
if [ ! -f "$BOOK_DIR/conf.py" ]; then
    echo "ERROR: $BOOK_DIR/conf.py not found — run 01-quickstart.sh first."
    exit 1
fi

# --- 1. Append our settings to conf.py --------------------------------------
#
# The 'EOF' below is wrapped in single quotes on purpose. That tells the shell
# to copy every line that follows EXACTLY as written, all the way to the line
# that says EOF — including every backslash. That matters because the LaTeX
# preamble further down is full of backslashes we do not want touched.

cat >> "$BOOK_DIR/conf.py" <<'EOF'

# =====================================================================
# gacalc book settings (originally generated by the sphinx-book-pipeline
# scaffold; those scripts are removed once the book builds, so the setup
# lives here now -- see the repo's git history for how it was produced)
# ---------------------------------------------------------------------
# Python reads this file from top to bottom, so anything we set again
# down here OVERRIDES the default that sphinx-quickstart wrote above
# (for example, the HTML theme).
# =====================================================================

# The "furo" theme: clean, modern, automatic light/dark. Same theme the
# modelviewprojection book uses, instead of the Sphinx default.
html_theme = "furo"

# Our own stylesheet, loaded on top of the theme's own CSS. It lives in
# the _static/ folder that sphinx-quickstart created.
html_css_files = ["custom.css"]

# The Sphinx add-ons ("extensions") this book turns on:
extensions = [
    "sphinx.ext.autodoc",       # copy docstrings out of the gacalc source
    "sphinx.ext.napoleon",      # read Google / NumPy style docstrings
    "sphinx.ext.viewcode",      # add a "[source]" link beside documented code
    "sphinx.ext.mathjax",       # draw the math in the HTML using MathJax
    "sphinx.ext.imgconverter",  # convert SVG pictures so the PDF can use them
    "nbsphinx",                 # let Jupyter notebooks become book pages
    "myst_nb",                  # kept exactly as modelviewprojection has it
]

# How autodoc behaves: document every member, keep them in source order,
# and include the __init__ / __call__ / arithmetic operator methods that
# a geometric-algebra library actually cares about.
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__, __call__, __add__, __sub__, __mul__, __rmul__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}

# Tell MathJax which delimiters mean "this is math":
#   $...$  and  \(...\)   for math inside a sentence
#   $$...$$ and \[...\]   for a centered equation on its own line
mathjax3_config = {
    "tex": {
        "inlineMath": [["$", "$"], ["\\(", "\\)"]],
        "displayMath": [["$$", "$$"], ["\\[", "\\]"]],
    },
}

# ---- PDF (LaTeX) settings -------------------------------------------
# Build the PDF with LuaLaTeX instead of the default pdfLaTeX. Reason:
# gacalc's docstrings contain real Unicode math characters (things like
# the square-root sign and subscripts). pdfLaTeX stops with an error on
# those; LuaLaTeX prints them just fine.
latex_engine = "lualatex"

# Left to itself LuaLaTeX would switch the index builder to "xindy",
# which drags in a large extra dependency. The plain "makeindex" is
# perfectly good for this book, so keep it.
latex_use_xindy = False

# A short LaTeX preamble so pictures stay where we put them and default
# to half the text width. r"""...""" is a "raw" string, meaning the
# backslashes are kept exactly as typed.
latex_elements = {
    "preamble": r"""
\usepackage{graphicx}
\usepackage{float}
\makeatletter
\def\fps@figure{H}
\setkeys{Gin}{width=0.5\textwidth}
\makeatother
""",
}

# A couple of Markdown niceties, matching modelviewprojection.
myst_enable_extensions = ["colon_fence", "dollarmath"]

# If a notebook page is slow to run, allow up to ten minutes for it.
nb_execution_timeout = 600
EOF

# --- 2. Replace the front page ----------------------------------------------
# sphinx-quickstart wrote a generic index.rst. Overwrite it with ours. The
# ">" (single arrow) starts the file fresh each time this script runs.

cat > "$BOOK_DIR/index.rst" <<'EOF'
Plotting On Crappy Graph Paper
==============================

The gacalc book. (Chapters coming later — this is the skeleton.)

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   api
EOF

# --- 3. Write the API page --------------------------------------------------
# `automodule` tells autodoc to read one Python module and print its
# docstrings. We point it at gacalc's hand-written, well-documented modules so
# the empty book already has real content to show.

cat > "$BOOK_DIR/api.rst" <<'EOF'
API Reference
=============

``gacalc.base``
---------------

.. automodule:: gacalc.base
   :members:

``gacalc.functions``
--------------------

.. automodule:: gacalc.functions
   :members:

``gacalc.transforms``
---------------------

.. automodule:: gacalc.transforms
   :members:
EOF

# --- 4. Write a starter stylesheet ------------------------------------------
# Empty on purpose for now: it exists so html_css_files above has a real file
# to load, and gives us one obvious place to add style tweaks later.

cat > "$BOOK_DIR/_static/custom.css" <<'EOF'
/* Custom styles for the gacalc book. Add overrides here as needed. */
EOF

# --- 5. Create the output/ folder the build copies into ---------------------
# `make docs` builds the book inside the container and copies the finished
# HTML/PDF into this folder. Git ignores the built files (they are regenerated),
# but we keep the empty folder itself with a .gitkeep so the folder always
# exists for the container to write into.
mkdir -p output
touch output/.gitkeep

echo "Done. Configured $BOOK_DIR/ (conf.py, index.rst, api.rst, _static/custom.css)"
echo "      and created output/ for the build to copy into."
echo "Next: build it with the repo's  make docs  target (HTML + PDF)."
